repaygithub/cactus

- .circleci/config.yml
CACTUS-16 :: CI for cactus design-system and framework
> chore(): add circle ci configuration

- .circleci/config.yml
- README.md
- examples/standard/package.json
- modules/cactus-theme/package.json
> fix(): use local cactus-theme in ci

- modules/cactus-theme/index.ts
- modules/cactus-web/src/Button/__snapshots__/Button.test.tsx.snap
- modules/cactus-web/src/TextButton/TextButton.mdx
- modules/cactus-web/src/TextButton/TextButton.story.tsx
- modules/cactus-web/src/TextButton/TextButton.test.tsx
- modules/cactus-web/src/TextButton/TextButton.tsx
- modules/cactus-web/src/TextButton/__snapshots__/TextButton.test.tsx.snap
- yarn.lock
> feat(cactus-web): Add text buttons

- modules/cactus-web/src/TextButton/TextButton.tsx
- modules/cactus-web/src/TextButton/__snapshots__/TextButton.test.tsx.snap
> style(cactus-web): Remove text button outlines

- examples/standard/package.json
- modules/cactus-fwk/package.json
- modules/cactus-i18n/package.json
- modules/cactus-icons/package.json
- modules/cactus-theme/package.json
- modules/cactus-web/package.json
- yarn.lock
Also added the `cleanup` command to modules which were missing it.
> chore(): upgrade @repay/scripts version

- package.json
- scripts/build-storybooks.js
- yarn.lock
> chore(): script to build and deploy stories as gh-pages

- docs/Components/API Documentation.md
- modules/cactus-web/src/CheckBox/CheckBox.mdx
- modules/cactus-web/src/CheckBox/CheckBox.story.tsx
- modules/cactus-web/src/CheckBox/CheckBox.test.tsx
- modules/cactus-web/src/CheckBox/CheckBox.tsx
- modules/cactus-web/src/CheckBox/__snapshots__/CheckBox.test.tsx.snap
- modules/cactus-web/src/custom.d.ts
> feat(cactus-web): Add checkbox component

- modules/cactus-web/src/RadioButton/RadioButton.mdx
- modules/cactus-web/src/RadioButton/RadioButton.story.tsx
- modules/cactus-web/src/RadioButton/RadioButton.test.tsx
- modules/cactus-web/src/RadioButton/RadioButton.tsx
- modules/cactus-web/src/RadioButton/__snapshots__/RadioButton.test.tsx.snap
> feat(cactus-web): Add radio buttons

- modules/cactus-web/src/Toggle/Toggle.mdx
- modules/cactus-web/src/Toggle/Toggle.story.tsx
- modules/cactus-web/src/Toggle/Toggle.test.tsx
- modules/cactus-web/src/Toggle/Toggle.tsx
- modules/cactus-web/src/Toggle/__snapshots__/Toggle.test.tsx.snap
> feat(cactus-web): Add toggles

- modules/cactus-web/src/Label/Label.mdx
- modules/cactus-web/src/Label/Label.story.tsx
- modules/cactus-web/src/Label/Label.test.tsx
- modules/cactus-web/src/Label/Label.tsx
- modules/cactus-web/src/Label/__snapshots__/Label.test.tsx.snap
Probably the easiest component yet 🤣
> feat(cactus-web): Add common label component

- modules/cactus-web/src/TextButton/TextButton.story.tsx
- modules/cactus-web/src/TextButton/TextButton.test.tsx
- modules/cactus-web/src/TextButton/TextButton.tsx
- modules/cactus-web/src/TextButton/__snapshots__/TextButton.test.tsx.snap
- modules/cactus-web/src/storySupport/DarkMode.tsx
> feat(cactus-web): Add danger variant to TextButton

- examples/standard/package.json
- examples/theme-components/package.json
- modules/cactus-fwk/package.json
- modules/cactus-i18n/package.json
- modules/cactus-web/package.json
- modules/cactus-web/src/CheckBox/CheckBox.tsx
- modules/cactus-web/src/CheckBox/__snapshots__/CheckBox.test.tsx.snap
- modules/cactus-web/src/CheckBoxField/CheckBoxField.mdx
- modules/cactus-web/src/CheckBoxField/CheckBoxField.story.tsx
- modules/cactus-web/src/CheckBoxField/CheckBoxField.test.tsx
- modules/cactus-web/src/CheckBoxField/CheckBoxField.tsx
- modules/cactus-web/src/CheckBoxField/__snapshots__/CheckBoxField.test.tsx.snap
- modules/cactus-web/src/helpers/generateId.ts
- modules/cactus-web/src/helpers/useId.ts
- modules/cactus-web/src/index.ts
- website/package.json
- website/yarn.lock
- yarn.lock
At long last! Checkbox fields! I also refactored `CheckBox` a bit so that it uses `DetailedHTMLProps`, and upgraded `@types/react` while I was at it.
> Checkbox field

- modules/cactus-web/src/TextButton/TextButton.tsx
- modules/cactus-web/src/TextButton/__snapshots__/TextButton.test.tsx.snap
> feat(cactus-web): text button should not strike-through on disabled

- modules/cactus-icons/.storybook/config.js
- modules/cactus-web/.storybook/config.js
> fix(): remove deprecated storybook prop

- modules/cactus-web/src/Button/Button.story.tsx
- modules/cactus-web/src/Button/Button.test.tsx
- modules/cactus-web/src/Button/Button.tsx
- modules/cactus-web/src/Button/__snapshots__/Button.test.tsx.snap
> feat(cactus-web): Style svgs as children of Buttons

- examples/standard/package.json
- examples/theme-components/package.json
- modules/cactus-icons/package.json
- modules/cactus-theme/package.json
- modules/cactus-web/package.json
- website/package.json
I wanted to make a separate PR for this just to be safe...I always get nervous pushing things straight to master, and a total of three packages were published 😄
> Publish packages

- modules/cactus-icons/stories/Icons.story.tsx
- modules/cactus-icons/svgr.config.js
- modules/cactus-web/.storybook/addons.js
- modules/cactus-web/.storybook/config.js
- modules/cactus-web/cactus-addon/constants.js
- modules/cactus-web/cactus-addon/index.tsx
- modules/cactus-web/cactus-addon/register.jsx
- modules/cactus-web/package.json
- modules/cactus-web/scripts/make-component.js
- modules/cactus-web/src/Button/Button.story.tsx
- modules/cactus-web/src/Button/Button.test.tsx
- modules/cactus-web/src/Button/Button.tsx
- modules/cactus-web/src/Button/__snapshots__/Button.test.tsx.snap
- modules/cactus-web/src/IconButton/IconButton.story.tsx
- modules/cactus-web/src/Spinner/Spinner.mdx
- modules/cactus-web/src/Spinner/Spinner.story.tsx
- modules/cactus-web/src/Spinner/Spinner.test.tsx
- modules/cactus-web/src/Spinner/Spinner.tsx
- modules/cactus-web/src/Spinner/__snapshots__/Spinner.test.tsx.snap
- modules/cactus-web/src/TextButton/TextButton.story.tsx
- yarn.lock
Also includes the cactus-addon for storybook that allows manipulating the theme.
> Adds spinner and loading button state

- modules/cactus-web/scripts/make-component.js
Add new component to the list of exports when using the new command
> chore(cactus-web): export new component from index

- modules/cactus-web/src/Button/Button.tsx
- modules/cactus-web/src/Button/__snapshots__/Button.test.tsx.snap
- modules/cactus-web/src/TextButton/TextButton.tsx
- modules/cactus-web/src/TextButton/__snapshots__/TextButton.test.tsx.snap
Fixes the focus outline issue that the channels devs were seeing this morning
> fix(cactus-web): Fix focus outline on buttons

- modules/cactus-theme/index.ts
- modules/cactus-web/src/Link/Link.story.tsx
- modules/cactus-web/src/Link/Link.test.tsx
- modules/cactus-web/src/Link/Link.tsx
- modules/cactus-web/src/Link/__snapshots__/Link.test.tsx.snap
- modules/cactus-web/src/StyleProvider/StyleProvider.tsx
Adds a new color to the theme and updates the link styles
> feat(cactus-web): Apply new link designs

- website/src/components/Layout.tsx
- website/src/pages/design-system/shared-styles.tsx
- website/src/pages/design-system/typography.tsx
docs(website): Update website pages for mobile view. Changed typography table style for mobile. Clear floating elements in shared-styles.
> Design system pages

- docs/Framework/API/Error Boundary.md
- modules/cactus-fwk/package.json
- modules/cactus-fwk/src/AppRoot.tsx
- modules/cactus-fwk/src/ErrorBoundary.tsx
- modules/cactus-fwk/src/index.ts
- modules/cactus-fwk/tests/ErrorBoundary.test.tsx
- yarn.lock
> feat(cactus-fwk): Add error boundary component

- website/src/components/PropsTable.tsx
- website/src/templates/GenericTemplate.tsx
> website(docs): update props table for mobile view.

- website/gatsby-node.js
- website/src/components/Layout.tsx
- website/src/helpers/debounce.ts
Makes the sidebar mobile friendly and drastically improves the performance of the docgen during development through caching.
> Docs mobile sidebar

- modules/cactus-web/package.json
Updates the distributable names to match type, corrects the repository name, and deduplicates building the types.
> chore(cactus-web): update package definitions and fields

- modules/cactus-web/src/StepAvatar/StepAvatar.mdx
- modules/cactus-web/src/StepAvatar/StepAvatar.story.tsx
- modules/cactus-web/src/StepAvatar/StepAvatar.test.tsx
- modules/cactus-web/src/StepAvatar/StepAvatar.tsx
- modules/cactus-web/src/StepAvatar/__snapshots__/StepAvatar.test.tsx.snap
> feat(cactus-web): Implemented interactive step story.

- modules/cactus-web/src/Avatar/Avatar.tsx
> fix(cactus-web): Updated avatar colors to colors that are in the theme.

- CHANGELOG.md
First time updating the changelog so I wanted to make a PR for it. I added all of the commits that I felt were important since the last changelog commit. I added them in reverse order too, so the most recent commits are at the top. I believe that's how it should be structured.
> chore(): Update changelog

- docs/Internationalization/API Documentation.md
- examples/standard/src/App.tsx
- examples/standard/src/containers/Home.tsx
- examples/standard/src/i18nController.ts
- examples/standard/src/locales/en/global.js
- examples/standard/src/locales/en/terms.js
- examples/standard/src/locales/es/global.js
- examples/standard/src/locales/es/terms.js
- modules/cactus-i18n/src/BaseI18nController.ts
- modules/cactus-i18n/src/Components.tsx
- modules/cactus-i18n/src/hooks.ts
- modules/cactus-i18n/tests/i18n.test.tsx
> feat(cactus-i18n): allow section language override

- modules/cactus-web/src/Accordion/Accordion.tsx
- modules/cactus-web/src/Accordion/__snapshots__/Accordion.test.tsx.snap
> fix(cactus-web): Fix Accordion not closing bug

- modules/cactus-web/src/FieldWrapper/FieldWrapper.story.tsx
- modules/cactus-web/src/FileInput/FileInput.tsx
- modules/cactus-web/src/FileInput/__snapshots__/FileInput.test.tsx.snap
- modules/cactus-web/src/FileInputField/__snapshots__/FileInputField.test.tsx.snap
- modules/cactus-web/src/SelectField/SelectField.tsx
- modules/cactus-web/src/SelectField/__snapshots__/SelectField.test.tsx.snap
- modules/cactus-web/src/StatusMessage/StatusMessage.tsx
- modules/cactus-web/src/TextArea/TextArea.tsx
- modules/cactus-web/src/TextArea/__snapshots__/TextArea.test.tsx.snap
- modules/cactus-web/src/TextAreaField/TextAreaField.tsx
- modules/cactus-web/src/TextAreaField/__snapshots__/TextAreaField.test.tsx.snap
- modules/cactus-web/src/TextInput/TextInput.tsx
- modules/cactus-web/src/TextInput/__snapshots__/TextInput.test.tsx.snap
- modules/cactus-web/src/TextInputField/TextInputField.tsx
- modules/cactus-web/src/TextInputField/__snapshots__/TextInputField.test.tsx.snap
> feat(cactus-web): update styles for input statuses

- modules/cactus-web/src/Accordion/Accordion.story.tsx
- modules/cactus-web/src/Accordion/Accordion.test.tsx
- modules/cactus-web/src/Accordion/Accordion.tsx
- modules/cactus-web/src/Accordion/__snapshots__/Accordion.test.tsx.snap
Fixes the issue where the height of the accordion body wouldn't grow with it's content. Also implements a dynamic length of animation based on how far the animation is. If the accordion is already open it no longer animates.
> fix(cactus-web): adjust accordion height when open

- modules/cactus-web/src/Select/Select.tsx
> fix(cactus-web): Allow number values in Select PropTypes

- modules/cactus-web/src/TextArea/TextArea.story.tsx
- modules/cactus-web/src/TextArea/TextArea.tsx
- modules/cactus-web/src/TextArea/__snapshots__/TextArea.test.tsx.snap
- modules/cactus-web/src/TextAreaField/TextAreaField.story.tsx
- modules/cactus-web/src/TextAreaField/__snapshots__/TextAreaField.test.tsx.snap
> feat(cactus-web): Add resize prop to TextArea

- examples/standard/src/containers/Home.tsx
- modules/cactus-web/src/Alert/Alert.story.tsx
- modules/cactus-web/src/Select/Select.story.tsx
- modules/cactus-web/src/Select/Select.test.tsx
- modules/cactus-web/src/Select/Select.tsx
- modules/cactus-web/src/Select/__snapshots__/Select.test.tsx.snap
- modules/cactus-web/src/SelectField/SelectField.story.tsx
- modules/cactus-web/src/SelectField/SelectField.tsx
- modules/cactus-web/src/SelectField/__snapshots__/SelectField.test.tsx.snap
[CACTUS-174]
BREAKING: onFocus will be properly called on Select click
and the onChange handler for Select has expanded value types.
> feat(cactus-web): Select allows multiselect

- modules/cactus-web/src/Select/Select.tsx
- modules/cactus-web/src/Select/__snapshots__/Select.test.tsx.snap
- modules/cactus-web/src/SelectField/__snapshots__/SelectField.test.tsx.snap
Fixes the select height issue we found today
> fix(cactus-web): Set select height to 32px

- modules/cactus-web/src/Select/Select.test.tsx
- modules/cactus-web/src/Select/Select.tsx
Unfortunately, I couldn't make the tests work with `act()` like we talked about, but hopefully this is good enough. 😄
> fix(cactus-web): Add value to select memoization

- modules/cactus-web/package.json
- modules/cactus-web/src/Select/Select.test.tsx
- modules/cactus-web/src/Select/Select.tsx
- modules/cactus-web/src/helpers/polyfills.ts
Fixes the issues that Jim noticed in my multiselect PR:
- Clicking the checkbox does add/remove options to and from the values now
- The clickable area has been increased for the close button on the value tags
Update: I had to fix a bug in IE that prevented the value tags from being removed with the x button by capturing the click events higher in the DOM. Also set `pointer-events` to `none` on the checkboxes so they can be clicked in IE
> Multiselect Improvements

- modules/cactus-web/src/ToggleField/ToggleField.tsx
- modules/cactus-web/src/ToggleField/__snapshots__/ToggleField.test.tsx.snap
> refactor(cactus-web): Swap location of toggle & label in ToggleField

- modules/cactus-web/src/DateInput/DateInput.mdx
- modules/cactus-web/src/DateInput/DateInput.test.tsx
- modules/cactus-web/src/DateInput/DateInput.tsx
- modules/cactus-web/src/DateInputField/DateInputField.mdx
This is non-breaking because DateInput has not yet been released.
> feat(cactus-web): null value to DateInput raises Date

- README.md
- package.json
- scripts/release.js
- yarn.lock
Now you can execute `yarn release [module] [new version]` at the root and it will run you through the script to clean, build, publish, and commit the new release; then it will generate and commit the updated change log.
> chore(): adds release and changelog script

- modules/cactus-web/src/Select/Select.test.tsx
- modules/cactus-web/src/Select/Select.tsx
Detects when values are passed that don't exist in options, and then adds them
> fix(cactus-web): Detect values that need to be added to options

- modules/cactus-web/src/Select/Select.test.tsx
- modules/cactus-web/src/Select/Select.tsx
Adds the fix for the `relatedTarget` issues we were seeing in the channels integration tests
> Related Targets Fixes

- modules/cactus-web/src/DateInput/DateInput.test.tsx
- modules/cactus-web/src/DateInput/DateInput.tsx
- modules/cactus-web/src/MenuButton/MenuButton.tsx
- modules/cactus-web/src/MenuButton/__snapshots__/MenuButton.test.tsx.snap
Two fixes to address bugs found during implementation.
> Implementation fixes

- modules/cactus-web/src/Select/Select.test.tsx
- modules/cactus-web/src/Select/Select.tsx
> refactor(cactus-web): Update wording on no options placeholder

- modules/cactus-web/src/DateInput/DateInput.tsx
- modules/cactus-web/src/DateInput/__snapshots__/DateInput.test.tsx.snap
- modules/cactus-web/src/DateInputField/__snapshots__/DateInputField.test.tsx.snap
Fixes multiple issues related to DateInputs on Firefox and Mobile Keyboard events.
> Date input bug fixes

- modules/cactus-web/src/TextInput/TextInput.tsx
- modules/cactus-web/src/helpers/dates.ts
- modules/cactus-web/tests/dates.test.ts
* feat(cactus-web): allow refs on TextInput for focus control
* fix(cactus-web): stabilize time on large year changes in DateInput
> Feature and fix to finish the form elements

- examples/mock-ebpp/src/components/FieldsAccordion.tsx
- examples/mock-ebpp/src/containers/rules.tsx
- examples/mock-ebpp/src/index.tsx
- examples/mock-ebpp/tests/helpers/actions.ts
- examples/mock-ebpp/tests/integration.test.ts
- examples/mock-ebpp/types.ts
- modules/cactus-web/src/Accordion/Accordion.mdx
- modules/cactus-web/src/Accordion/Accordion.story.tsx
- modules/cactus-web/src/Accordion/Accordion.test.tsx
- modules/cactus-web/src/Accordion/Accordion.tsx
- modules/cactus-web/src/Accordion/__snapshots__/Accordion.test.tsx.snap
- package.json
- yarn.lock
Adds support for a render prop as well as the new outline variant to the accordion component, let me know if you have any questions
> feat(cactus-web): Add outline variant & render prop to accordion

- modules/cactus-web/src/Select/Select.story.tsx
- modules/cactus-web/src/Select/Select.tsx
If you know how I might be able to test this, let me know. I tried a couple things and did some research on it but I couldn't find anything. I don't know if it's possible. I did modify a story, though, so that you can see it in action.
> fix(cactus-web): Add overflow ellipsis to select

- CONTRIBUTING.md
- docs/Coding Best Practices/README.md
- docs/Internationalization/API Documentation.md
- docs/README.md
- website/README.md
- website/gatsby-config.js
- website/gatsby-node.js
Cherry picked the commits that didn't touch dependencies from #211 since we can't do the styled-components upgrade yet
> Website Knowledge Transfer

- examples/theme-components/src/containers/AccessibleField.tsx
- examples/theme-components/src/containers/Accordion.tsx
- examples/theme-components/src/containers/Alert.tsx
- examples/theme-components/src/containers/Avatar.tsx
- examples/theme-components/src/containers/Breadcrumb.tsx
- examples/theme-components/src/containers/DateInput.tsx
- examples/theme-components/src/containers/DateInputField.tsx
- examples/theme-components/src/containers/FieldWrapper.tsx
- examples/theme-components/src/containers/FileInput.tsx
- examples/theme-components/src/containers/FileInputField.tsx
- examples/theme-components/src/containers/Flex.tsx
- examples/theme-components/src/containers/FormExample.tsx
- examples/theme-components/src/containers/Grid.tsx
- examples/theme-components/src/containers/Home.tsx
- examples/theme-components/src/containers/IconButton.tsx
- examples/theme-components/src/containers/MenuButton.tsx
- examples/theme-components/src/containers/Modal.tsx
- examples/theme-components/src/containers/StepAvatar.tsx
- examples/theme-components/src/index.tsx
[CACTUS-63]
[CACTUS-63]: https://repayonline.atlassian.net/browse/CACTUS-63
> feat(cactus-web): Form Elements Documentation

- modules/cactus-theme/src/theme.ts
- modules/cactus-web/src/Button/Button.test.tsx
- modules/cactus-web/src/Button/Button.tsx
- modules/cactus-web/src/Button/__snapshots__/Button.test.tsx.snap
- modules/cactus-web/src/FileInput/__snapshots__/FileInput.test.tsx.snap
- modules/cactus-web/src/FileInputField/__snapshots__/FileInputField.test.tsx.snap
- modules/cactus-web/src/MenuButton/MenuButton.test.tsx
- modules/cactus-web/src/MenuButton/MenuButton.tsx
- modules/cactus-web/src/MenuButton/__snapshots__/MenuButton.test.tsx.snap
- modules/cactus-web/src/Modal/__snapshots__/Modal.test.tsx.snap
- modules/cactus-web/src/StyleProvider/StyleProvider.tsx
- modules/cactus-web/src/TextButton/TextButton.test.tsx
- modules/cactus-web/src/TextButton/TextButton.tsx
- modules/cactus-web/src/TextButton/__snapshots__/TextButton.test.tsx.snap
[CACTUS-244]
[CACTUS-244]: https://repayonline.atlassian.net/browse/CACTUS-244
> feat(cactus-web): Component theme changes phase one

- package.json
- yarn.lock
I was about to make my first real commit, and I noticed that we use a standard commit message template.  In the past, for projects where this was the case, I used a tool called commitizen to make it easier to conform to this template.  I thought I'd give it a whirl here and create a separate PR rather than wrap it up in my other stuff.
What do you guys think?
Pull down the branch and run `yarn` in the root.  To make a commit, run `yarn commit` instead of `git commit`.  It will walk you through the template.
> Add commitizen

- modules/cactus-web/src/Accordion/Accordion.test.tsx
- modules/cactus-web/src/Accordion/Accordion.tsx
- modules/cactus-web/src/Accordion/__snapshots__/Accordion.test.tsx.snap
- modules/cactus-web/src/Card/Card.test.tsx
- modules/cactus-web/src/Card/Card.tsx
- modules/cactus-web/src/Card/__snapshots__/Card.test.tsx.snap
I looked at the icon buttons but I really don't think we should change anything about them.
To test, just check out this branch and have a look at the card & accordion components and play around with the theming options. Make sure to look at both the `simple` and `outline` accordion variants
> Icon, Card, & Accordion Theming

- docs/Components/API Documentation.md
- docs/Components/README.md
- docs/Framework/API/Error Boundary.md
- docs/Framework/API/Feature Flags.md
- docs/Framework/API/README.md
- docs/Framework/README.md
- docs/Icons/README.md
- docs/Internationalization/API Documentation.md
- docs/Internationalization/Project Fluent.md
- docs/Internationalization/README.md
- docs/README.md
- website/src/components/Layout.tsx
- website/src/pages/stories.tsx
Fixed some broken links ont the docs page and sidebar menu bug
[CACTUS-248]
[CACTUS-248]: https://repayonline.atlassian.net/browse/CACTUS-248
> docs(website): Docs Website Imporvements

- .eslintignore
- .prettierignore
My bad for gumming up the lint machine!
> Ignore transpiled testing-library files when linting

- scripts/release.js
Ticket: https://repayonline.atlassian.net/browse/CACTUS-289
This just pulls in an old commit from James a while back making some improvements on the release script. The main change is that the script will list out all commits relevant to the package being released if you don't provide a version number. This makes it easier to determine if there are breaking changes.
1. Run `yarn release` at the root
2. Select a package
3. Observe that all of the commits are then listed to you
4. Cancel before anything is _actually_ released 😃
> CACTUS-289 :: Release Script Upgrades

- yarn.lock
This fixes a known security vulnerability.  I don't think we were affected, but it can't hurt.
> Upgrade kind-of v6 package

- examples/theme-components/src/containers/Modal.tsx
- modules/cactus-web/src/Modal/Modal.mdx
- modules/cactus-web/src/Modal/Modal.story.tsx
- modules/cactus-web/src/Modal/Modal.test.tsx
- modules/cactus-web/src/Modal/Modal.tsx
- modules/cactus-web/src/Modal/__snapshots__/Modal.test.tsx.snap
[CACTUS-265]
[CACTUS-265]: https://repayonline.atlassian.net/browse/CACTUS-265
> Modal redesign

- docs/Internationalization/Getting Started.md
[CACTUS-262]
[CACTUS-262]: https://repayonline.atlassian.net/browse/CACTUS-262
> docs(cactus-i18n): fixed example for i18nController action in docs

- yarn.lock
Since this is all client-side, I still think we're probably fine, but it doesn't hurt to keep
up-to-date
> Upgrade more potential vulnerabilities

- modules/cactus-web/src/DataGrid/__snapshots__/DataGrid.test.tsx.snap
I noticed the tests in master failed when my `DataGrid` PR was merged. Looks like my branch was a bit behind so I didn't have the changes to the theme when I created the snapshot. This is just a PR to update it so we can get the CI pipeline passing in master
> Fix DataGrid Snapshot

- modules/cactus-web/src/FileInput/FileInput.tsx
- modules/cactus-web/src/FileInput/__snapshots__/FileInput.test.tsx.snap
- modules/cactus-web/src/FileInputField/__snapshots__/FileInputField.test.tsx.snap
Ticket and testing: https://repayonline.atlassian.net/browse/CACTUS-309
Build will fail until we merge in Dhalton's PR
> Fixe FileInput error/disabled border thickness

- modules/cactus-web/src/FileInput/FileInput.tsx
This is a fast follow to https://repayonline.atlassian.net/browse/CACTUS-309.
All I did was ensure that the border radius respects the theme, as discussed here: https://repayonline.atlassian.net/browse/CACTUS-309?focusedCommentId=53366
So that's all you need to test!
> CACTUS-309 :: Fix FileInput border radius

- modules/cactus-icons/stories/Icons.story.tsx
[CACTUS-317]
[CACTUS-317]: https://repayonline.atlassian.net/browse/CACTUS-317
> fix(cactus-icons): fix bug with icons in storybook

- README.md
- examples/mock-ebpp/README.md
- examples/standard/README.md
- examples/theme-components/README.md
Ticket: https://repayonline.atlassian.net/browse/CACTUS-315
Pretty straightforward, Just added some quick notes on how to run the example apps & linked back to that section of the README in each app's README.
Let me know if you think I missed any steps or anything like that.
> docs: Add instructions on how to build & run example apps

- docs/Components/README.md
- docs/Framework/README.md
- docs/Getting-Started/README.md
- docs/Icons/README.md
- docs/Internationalization/README.md
- docs/README.md
- docs/Theme/README.md
To review the docs
Launch the docs website: yarn docs start
On the sidebar there will be a Getting Started tab and there you'll find the docs.
There is also a link on the main page on the Getting Started section. This option is only available in the published version of the Website though
> Getting started docs

- examples/mock-ebpp/src/components/MenuBar.tsx
- examples/mock-ebpp/src/containers/home.tsx
- examples/mock-ebpp/src/containers/payment-history-report.tsx
- examples/mock-ebpp/src/index.tsx
- examples/mock-ebpp/tests/menubar-integration.test.ts
Run the mock-ebpp tests with any browser you want and check that everything passes
> feat(mock-ebpp): integration tests for the MenuBar in mock-ebpp

- examples/mock-ebpp/src/components/MenuBar.tsx
- examples/mock-ebpp/tests/menubar-integration.test.ts
- modules/cactus-web/src/DateInput/DateInput.story.tsx
Run: 
- yarn w mock-ebpp test with a specified browser
- yarn w mock-ebpp test:ci
Check that everything passes as expected
> Integration test menu bar overflow

- examples/mock-ebpp/tests/helpers/actions.ts
- modules/cactus-web/README.md
- modules/cactus-web/src/Select/Select.test.tsx
- modules/cactus-web/src/Select/Select.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-198
So I finally figured out why VoiceOver wasn't able to focus on the input...for some reason it didn't like it being set to `role="search"`. When I changed it to `role="textbox"`, VoiceOver was able to focus on & type in the input as expected.
I added some docs outlining how you can connect an iPhone to a Mac & test Storybooks locally, but obviously that only works if you're using both an iOS device and a MacOS device. This leaves me with a couple of questions:
1. Should I add some steps to connect other devices to Mac, such as Android? Could be useful, as I have no idea what phones other members of the team have. Although I have no way to test it, so I wouldn't know if it actually works.
2. Should we include any docs for non-Mac …
> CACTUS-198 ::  Mobile Combobox Accessibility

- modules/cactus-web/src/ConfirmModal/__snapshots__/ConfirmModal.test.tsx.snap
- modules/cactus-web/src/TextInput/TextInput.tsx
- modules/cactus-web/src/TextInput/__snapshots__/TextInput.test.tsx.snap
- modules/cactus-web/src/TextInputField/__snapshots__/TextInputField.test.tsx.snap
[CACTUS-349]
[CACTUS-349]: https://repayonline.atlassian.net/browse/CACTUS-349
> fix(cactus-web): fix ie11 input alignment error

- modules/cactus-web/src/Select/Select.tsx
There is no easy way to test this since the select is pretty much working fine in the mock-ebpp, it faild for me just once or so.
I worked this solution with John who was the reporter and told me it worked just fine for him.
> Fix select focus

- modules/cactus-web/src/Card/Card.tsx
- modules/cactus-web/src/Card/__snapshots__/Card.test.tsx.snap
Ticket/UAT: https://repayonline.atlassian.net/browse/CACTUS-362
> CACTUS-362 :: Remove hard-coded text colors on nested cards

- modules/cactus-web/src/DataGrid/DataGrid.story.tsx
- modules/cactus-web/src/DataGrid/DataGrid.tsx
- modules/cactus-web/src/DataGrid/__snapshots__/DataGrid.test.tsx.snap
Ticket: https://repayonline.atlassian.net/browse/CACTUS-361
I added a knob in the DataGrid's story to turn on/off the sortable columns so we can test some of those ACs.
Open the DataGrid story and run through the ACs on the ticket making sure the top section is behaving as expected.
> CACTUS-361 :: DataGrid TopSection

- modules/cactus-web/src/Card/Card.story.tsx
- modules/cactus-web/src/Card/Card.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-363
1. Open the Card basic usage storybook.
2. Turn on/off the `useBoxShadow` toggle in the knobs & make sure the box shadow on the card behaves accordingly
> CACTUS-363 :: Card Box Shadow

- modules/cactus-web/src/RadioGroup/RadioGroup.mdx
- website/src/components/PropsTable.tsx
Build the docs page.
Go to ConfirmModal and make sure both Modal and ConfirmModal props exist. Also ensure no unwanted  props from node_modules are listed in other components
> Inherit props documentation

- modules/cactus-web/src/MenuButton/MenuButton.tsx
- modules/cactus-web/src/MenuButton/__snapshots__/MenuButton.test.tsx.snap
Ticket: https://repayonline.atlassian.net/browse/CACTUS-365
Bring up the `MenuButton` story in IE11 and press tab to focus on the button. You should see an outline around it to indicate that it has focus.
> CACTUS-365 :: IE11 MenuButton Fix

- modules/cactus-web/src/DataGrid/__snapshots__/DataGrid.test.tsx.snap
- modules/cactus-web/src/SplitButton/SplitButton.story.tsx
- modules/cactus-web/src/SplitButton/SplitButton.tsx
- modules/cactus-web/src/SplitButton/__snapshots__/SplitButton.test.tsx.snap
In  storybook, go to the basic usage split button, and test that the three variants match the Styleguide.
[CACTUS-354]
[CACTUS-354]: https://repayonline.atlassian.net/browse/CACTUS-354
> Splitbutton variants

- modules/cactus-web/src/Card/Card.mdx
- modules/cactus-web/src/Card/Card.story.tsx
- modules/cactus-web/src/Card/Card.test.tsx
- modules/cactus-web/src/Card/Card.tsx
- modules/cactus-web/src/Card/__snapshots__/Card.test.tsx.snap
Ticket: https://repayonline.atlassian.net/browse/CACTUS-375
Testing should be pretty simple; just bring up the storybook and use the new knobs to make sure all of the acceptance criteria are being met.
> CACTUS-375 :: Configurable Card Padding

- modules/cactus-web/src/Table/Table.story.tsx
- modules/cactus-web/src/Table/Table.tsx
- modules/cactus-web/src/Table/__snapshots__/Table.test.tsx.snap
There is a knew story for the Table in the storybook in which you can see the result. 
If you want to see a different length, or behavior for other cell, the text should be changed in the code because of the way this is calculated; it does not work as a knob.
[CACTUS-370]
[CACTUS-370]: https://repayonline.atlassian.net/browse/CACTUS-370
> fix(cactus-web): fix height of table with long values

- examples/standard/package.json
- yarn.lock
To test, just run `yarn w standard start`
> Upgrade cactus-fwk in standard example app

- modules/cactus-web/src/Accordion/Accordion.tsx
- modules/cactus-web/src/Breadcrumb/Breadcrumb.tsx
Ticket and testing: https://repayonline.atlassian.net/browse/CACTUS-408
> CACTUS-408 :: stop passing custom prop to DOM element in Accordion

- examples/mock-ebpp/package.json
- lerna.json
- package.json
- yarn.lock
Ticket: https://repayonline.atlassian.net/browse/CACTUS-410
Not really much to test here.  You can play around with `yarn release` if you'd like...just make sure to exit before you actually publish anything 😄
> CACTUS-410 :: Add Lerna to Cactus

- modules/cactus-web/src/Toggle/Toggle.tsx
- modules/cactus-web/src/Toggle/__snapshots__/Toggle.test.tsx.snap
- modules/cactus-web/src/ToggleField/__snapshots__/ToggleField.test.tsx.snap
To test:
Go to the toggle story, and make sure the disable style is applied correctly when "off" and "on"
[CACTUS-399]
[CACTUS-399]: https://repayonline.atlassian.net/browse/CACTUS-399
> fix(cactus-web): fix toggle disable style

- modules/cactus-web/src/Toggle/Toggle.tsx
- modules/cactus-web/src/Toggle/__snapshots__/Toggle.test.tsx.snap
- modules/cactus-web/src/ToggleField/__snapshots__/ToggleField.test.tsx.snap
The main thing to test is the Toggle story.  Make sure that the toggle itself looks good and that the ACs of https://repayonline.atlassian.net/browse/CACTUS-399 are met.
> Merging Toggle Changes into Cactus Web v4

- examples/mock-ebpp/run-ete-tests.js
- examples/standard/run-ete-tests.js
> Revert "Go back to running BrowserStack tests in parallel"

- .github/workflows/continuous-integration.yml
> Prevent GitHub Actions from running on tags

- modules/cactus-web/src/Tooltip/Tooltip.test.tsx
- modules/cactus-web/src/Tooltip/Tooltip.tsx
- modules/cactus-web/src/Tooltip/__snapshots__/Tooltip.test.tsx.snap
Ticket: https://repayonline.atlassian.net/browse/CACTUS-414
Open the Tooltip story and hover the icon to bring up the tooltip text. Move your mouse inside the tooltip popup and verify that it stays open as long as your mouse stays inside the content box.
> CACTUS-414 :: Tooltip Hover

- modules/cactus-web/.storybook/main.js
- modules/cactus-web/.storybook/preview.js
- modules/cactus-web/package.json
- yarn.lock
Test:
Run storybook and go to the Docs tab, explore it.
> Display src storybook

- .github/workflows/continuous-integration.yml
Ticket: https://repayonline.atlassian.net/browse/CACTUS-439
1. Check out this branch and use it as a base to create a new branch.
2. Make a change in a story that would cause the visual snapshot tests to fail
3. Commit your change and push up your branch
4. Wait for a new PR to be generated and make sure the name of the PR is based on its parent PR. The name should be `${parent-branch-name}-patch`.
5. Optionally, you can make another change that would also cause more tests to fail and push that up to the same branch and make sure that the originally generated PR is updated instead and a new one is not created
> CACTUS-439 :: Fix Auto-Generated PRs

- modules/cactus-i18n/src/Components.tsx
- modules/cactus-icons/svgr.config.js
- modules/cactus-web/scripts/make-component.js
- modules/cactus-web/src/SplitButton/SplitButton.story.tsx
- modules/cactus-web/src/helpers/dates.ts
Ticket: https://repayonline.atlassian.net/browse/CACTUS-436
I've added links to the relevant SonarQube issues in the commit bodies, if you're interested.  Because of other things, I didn't actually check too many issues off the list in the two days allotted.  If you have any questions on any of the issues, please let me know.
The main thing to test would be i18n stuff.  Easiest way to do that would be to run `yarn build` with these changes and then run the Standard example app.
> CACTUS-436 :: SonarQube Fixes

- modules/cactus-web/src/Select/Select.story.tsx
- modules/cactus-web/src/StyleProvider/StyleProvider.tsx
[CACTUS-445]
[CACTUS-445]: https://repayonline.atlassian.net/browse/CACTUS-445
> fix(cactus-web): remove helvetica font from buttons

- modules/cactus-web/src/Modal/Modal.mdx
- modules/cactus-web/src/Modal/Modal.story.tsx
- modules/cactus-web/src/Modal/Modal.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-455
Pretty straightforward...to test you can bring up the Modal story and set the width using the width knob.
> CACTUS-455 :: Modal Width Override

- examples/theme-components/styled.d.ts
- examples/theme-components/tsconfig.json
- modules/cactus-theme/src/theme.ts
- modules/cactus-web/cactus-addon/index.tsx
- modules/cactus-web/src/Accordion/Accordion.story.tsx
- modules/cactus-web/src/ActionBar/ActionProvider.tsx
- modules/cactus-web/src/Button/Button.tsx
- modules/cactus-web/src/CheckBoxGroup/CheckBoxGroup.story.tsx
- modules/cactus-web/src/CheckBoxGroup/CheckBoxGroup.tsx
- modules/cactus-web/src/ConfirmModal/ConfirmModal.tsx
- modules/cactus-web/src/DataGrid/BottomSection.tsx
- modules/cactus-web/src/DataGrid/TopSection.tsx
- modules/cactus-web/src/DateInput/DateInput.tsx
- modules/cactus-web/src/DateInputField/DateInputField.tsx
- modules/cactus-web/src/FileInput/FileInput.tsx
- modules/cactus-web/src/FileInputField/FileInputField.tsx
- modules/cactus-web/src/Footer/Footer.story.tsx
- modules/cactus-web/src/Footer/Footer.tsx
- modules/cactus-web/src/IconButton/IconButton.tsx
- modules/cactus-web/src/Layout/Layout.tsx
- modules/cactus-web/src/MenuBar/MenuBar.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-447
* In Storybook, play around with a two-color theme.  Ensure that everything seems to be working normally when you edit both the primary and secondary colors.
* Ensure that the following components work as expected:
* ActionBar
* Button (disabled vs. non-disabled states)
* CheckBoxGroup
* ConfirmModal (icon and the variants)
* DataGrid (top and bottom sections)
* DateInput/DateInputField
* FileInput/FileInputField
* Footer (play around with adding/removing links and changing the screen size to ensure that the columns work correctly)
* Layout
* MenuBar
> CACTUS-447 :: SonarQube Fixes

- modules/cactus-web/src/Alert/Alert.story.tsx
- modules/cactus-web/src/Alert/Alert.tsx
- modules/cactus-web/src/Alert/__snapshots__/Alert.test.tsx.snap
https://repayonline.atlassian.net/browse/CACTUS-462
Seems like the issue was with flex-basis and/or flex-grow, somehow shrinking the button to 0 width. I took the opportunity to fix the text overflow as well, since it was on my mind from the Modal PR.
> CACTUS-462: make Alert close button visible in IE

- modules/cactus-web/package.json
- yarn.lock
https://repayonline.atlassian.net/browse/CACTUS-461
Doesn't seem like two days worth of work, does it? I spent the rest of the time trying to upgrade two of the security dependencies, but it inexplicably made the visual tests fail even though they passed locally. After a day of that I just gave up, before I started to feel the urge to commit suicide.
> CACTUS-461: Blackduck fixes 1

- docs/README.md
- docs/Tutorials/Responsive Web Design.md
- website/src/components/Layout.tsx
- website/src/pages/tutorials.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-471
I'm no tutorial expert, so all suggestions are welcome. I thought about doing something a little more...meaningful inside the cards, but I also wanted to keep it pretty simple so I don't take any attention away from the main focus, which is to build a responsive page using `Grid`.
Let me know what you think!
> CACTUS-471 :: Getting Started Tutorial

- modules/cactus-web/src/Alert/Alert.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-498
Pretty quick & easy. I'm not sure why the storyshots didn't update...I guess it wasn't able to detect the color change on such a small piece of a component. 🤷
> CACTUS-498 :: Alert Close Button Variants

- README.md
Link: [Cactus-506](https://repayonline.atlassian.net/browse/CACTUS-506)
> docs(cactus): storybook documentation 1.0

- modules/cactus-theme/src/theme.ts
- modules/cactus-theme/tests/theme.test.ts
- modules/cactus-web/cactus-addon/register.jsx
Ticket and UAT: https://repayonline.atlassian.net/browse/CACTUS-512
This was pretty straightforward, but let me know if I missed anything.
> CACTUS-512 :: Grayscale Theme

- docs/How-tos/Forms.md
- website/src/pages/how-tos.tsx
https://repayonline.atlassian.net/browse/CACTUS-514
So according to the Divio nomenclature, I think this came out as more of a reference guide than a how-to guide. How-tos are supposed to have numbered steps, basically, and the only steps I could come up with were (1) install Formik and (2) write a form; both of which are covered quite well already in the Formik docs. So instead I mostly covered how to combine Formik with our form elements, and any quirks or unexpected surprises I found while doing so.
> CACTUS-514 How-to Formik + Cactus

- modules/cactus-web/src/ConfirmModal/__snapshots__/ConfirmModal.test.tsx.snap
- modules/cactus-web/src/Modal/Modal.tsx
- modules/cactus-web/src/Modal/__snapshots__/Modal.test.tsx.snap
https://repayonline.atlassian.net/browse/CACTUS-518
Exactly as hard as it looks.
> CACTUS-518: correct margin issue with Modal in IE

- .github/workflows/continuous-integration.yml
- examples/mock-ebpp/tests/ui-config-integration.test.ts
> Change order of visual/integration tests

- examples/mock-ebpp/tests/ui-config-integration.test.ts
- modules/cactus-web/src/MenuBar/MenuBar.tsx
- modules/cactus-web/src/MenuBar/__snapshots__/MenuBar.test.tsx.snap
https://repayonline.atlassian.net/browse/CACTUS-520
> CACTUS-520: change side menu to alternating nested colors

- docs/Deep Dives/Front-End-Testing-Philosophy.md
- website/src/components/Layout.tsx
- website/src/pages/deep-dives.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-531
A lot of this is just paraphrasing Kent C. Dodds' blog posts and linking back to them. I believe all of the links are working in the docs site but if you come across any that don't, let me know.
As always, I'm open to any suggestions on how this can be improved!
> CACTUS-531 :: Front End Testing Philosophy

- modules/cactus-web/src/CheckBoxGroup/CheckBoxGroup.tsx
- modules/cactus-web/src/CheckBoxGroup/__snapshots__/CheckBoxGroup.test.tsx.snap
- modules/cactus-web/src/Fieldset/Fieldset.tsx
- modules/cactus-web/src/RadioGroup/RadioGroup.tsx
- modules/cactus-web/src/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
- modules/cactus-web/src/helpers/react.ts
The update here was to extract shared functionality from `RadioGroup` and `CheckBoxGroup` into the `Fieldset` component.  To test, make sure that everything works normally for both `RadioGroup` and `CheckBoxGroup`.
> CACTUS-545 :: SonarQube Updates

- modules/cactus-web/src/MenuBar/scroll.ts
Ticket and UAT: https://repayonline.atlassian.net/browse/CACTUS-561
Thankfully this was much easier than yesterday's ticket.
> CACTUS-561 :: Safari Menu Dropdown Bug

- modules/cactus-web/src/Select/Select.tsx
https://repayonline.atlassian.net/browse/CACTUS-584
Every time I look at this component I just want to refactor it to death. (Or rather to life, I suppose.) Still, this is one little bit cleaner.
> CACTUS-584 Remove redundant Select state

- actions/storyshots/Dockerfile
All of a sudden, Puppeteer is complaining about missing a library.  So...I added it back to fix the build.
> Fix broken build

- modules/cactus-web/src/helpers/scroll.ts
https://repayonline.atlassian.net/browse/CACTUS-603
As best I can tell, everything in that function is now an integer. Integer math banzai!
> CACTUS-603: fix floating point errors in `useScroll` hook

- modules/cactus-web/src/AccessibleField/AccessibleField.test.tsx
- modules/cactus-web/src/AccessibleField/AccessibleField.tsx
- modules/cactus-web/src/ActionBar/ActionBar.test.tsx
- modules/cactus-web/src/ActionBar/__snapshots__/ActionBar.test.tsx.snap
- modules/cactus-web/src/Alert/Alert.tsx
- modules/cactus-web/src/Avatar/Avatar.tsx
- modules/cactus-web/src/BrandBar/BrandBar.tsx
- modules/cactus-web/src/Breadcrumb/Breadcrumb.tsx
- modules/cactus-web/src/DataGrid/DataGrid.tsx
- modules/cactus-web/src/DataGrid/DataGridTable.tsx
- modules/cactus-web/src/DateInput/DateInput.story.tsx
- modules/cactus-web/src/DateInput/DateInput.tsx
- modules/cactus-web/src/Dimmer/Dimmer.tsx
- modules/cactus-web/src/Footer/Footer.tsx
- modules/cactus-web/src/Layout/Layout.tsx
- modules/cactus-web/src/PrevNext/PrevNext.tsx
- modules/cactus-web/src/Tag/Tag.tsx
- modules/cactus-web/src/Tooltip/Tooltip.test.tsx
- modules/cactus-web/src/Tooltip/Tooltip.tsx
- modules/cactus-web/src/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- modules/cactus-web/src/helpers/omit.ts
https://repayonline.atlassian.net/browse/CACTUS-597
I did a commit per component instead of my usual squash, so it could be helpful to go through this one commit at a time. Some of the commits also have fairly detailed commit messages where things weren't completely straightforward, so you can also read those to get more info.
Kind of weird how the components needing to be changed are all bunched up at the beginning of the alphabet: made me think this ticket was going to take a lot longer than it ended up taking.
> CACTUS-597: Prop Forwarding & `data-testid`

- docs/Theme/README.md
- modules/cactus-theme/src/theme.ts
- modules/cactus-theme/tests/theme.test.ts
- modules/cactus-web/src/ConfirmModal/ConfirmModal.tsx
- modules/cactus-web/src/DataGrid/BottomSection.tsx
- modules/cactus-web/src/DataGrid/TopSection.tsx
- modules/cactus-web/src/Header/Header.tsx
- modules/cactus-web/src/Modal/Modal.tsx
- modules/cactus-web/src/ScreenSizeProvider/ScreenSizeProvider.story.tsx
- modules/cactus-web/src/ScreenSizeProvider/ScreenSizeProvider.tsx
- modules/cactus-web/src/Select/Select.tsx
- modules/cactus-web/src/StyleProvider/StyleProvider.story.tsx
- modules/cactus-web/src/StyleProvider/StyleProvider.tsx
- modules/cactus-web/src/Tabs/Tabs.tsx
- modules/cactus-web/src/TextArea/TextArea.tsx
- modules/cactus-web/src/helpers/constants.ts
- modules/cactus-web/src/helpers/theme.ts
- modules/cactus-web/src/index.ts
Ticket: https://repayonline.atlassian.net/browse/CACTUS-665
1. Pull down this branch and run `yarn cleanup && yarn build && yarn web start`
2. Inspect some components that use breakpoints/media queries at different screen sizes and make sure they're behaving as they should at each respective screen size. Some good components to test with are:
- Layout
- BrandBar
- Footer
- Table
- DataGrid
- Basically any component that adjusts its display/layout depending on screen size.
> CACTUS-665 :: Require Media Queries

- modules/cactus-web/src/ColorPicker/ColorPicker.story.tsx
- modules/cactus-web/src/ColorPicker/ColorPicker.tsx
- modules/cactus-web/src/Dimmer/Dimmer.test.tsx
- modules/cactus-web/src/FileInput/FileInput.story.tsx
- modules/cactus-web/src/FocusLock/FocusLock.test.tsx
- modules/cactus-web/src/Header/Header.test.tsx
- modules/cactus-web/src/MenuButton/MenuButton.test.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-676
Just a couple of code smell fixes and adding some tests for coverage.
For testing just make sure `ColorPicker` & `FileInput` stories still work
> CACTUS-676 :: SonarQube Fixes

- modules/cactus-web/src/Calendar/Calendar.test.tsx
Fixes the test that broke when the month changed.
> CACTUS-697: fix test to account for outside dates

- modules/cactus-web/src/ActionBar/ActionBar.test.tsx
- modules/cactus-web/src/BrandBar/BrandBar.test.tsx
- modules/cactus-web/src/helpers/usePopup.ts
[CACTUS-733](https://repayonline.atlassian.net/browse/CACTUS-733)
> CACTUS-733 : MenuBug

- modules/cactus-web/src/BrandBar/BrandBar.tsx
https://repayonline.atlassian.net/browse/CACTUS-725
gg ez
> CACTUS-725 :: Profile Page Bug

- modules/cactus-web/src/Layout/Layout.test.tsx
[CACTUS-728](https://repayonline.atlassian.net/browse/CACTUS-728)
> CACUTS-728:: useLayout tests

- modules/cactus-theme/src/helpers/borders.ts
- modules/cactus-theme/tests/border-helpers.test.ts
- modules/cactus-web/src/CheckBox/CheckBox.tsx
https://repayonline.atlassian.net/browse/CACTUS-816
To be honest, I don't know if the `(p: ThemeProps) => Interpolation<ThemeProps>` is right. The ticket says it'd be complex to include that, and obviously what I'm doing isn't complex, so if it's incorrect let me know.
> CACTUS-816 :: borderSize types

- modules/cactus-form/src/DependentField.ts
- modules/cactus-form/src/Field.ts
- modules/cactus-form/src/config.ts
- modules/cactus-theme/src/theme.ts
- modules/cactus-web/src/Accordion/Accordion.tsx
- modules/cactus-web/src/Grid/Grid.story.tsx
- modules/cactus-web/src/TextArea/TextArea.tsx
https://repayonline.atlassian.net/browse/CACTUS-850
I didn't really see anything to do in `ui-tools` or `ui-private`, so this is it for the ticket. I started before I noticed the report was out of date, so the first two are things Danilo already fixed (or ignored), but I would rather have fixed in a different way.
I didn't bother with all the code duplication, just the two biggest contributors.
> CACTUS-850 Sonarqube

- examples/mock-ebpp/package.json
- examples/standard/package.json
Ticket: https://repayonline.atlassian.net/browse/CACTUS-789
Nothing to test manually. If the integration tests pass for this PR, that should be good enough.
> CACTUS-789 :: Removed Pinned Safari Version

- modules/cactus-web/src/Button/Button.test.tsx
- modules/cactus-web/src/Button/Button.tsx
[CACTUS-748](https://repayonline.atlassian.net/browse/CACTUS-748)
> CACTUS-748 :: Expose aria-live on Button

- docs/Forms/API Documentation.md
- modules/cactus-form/src/Field.ts
- modules/cactus-form/tests/form.test.tsx
Ticket & UAT: https://repayonline.atlassian.net/browse/CACTUS-900
> CACTUS-900 :: Configurable Error Messages

- yarn.lock
> chore: update lockfile with new cactus pkg versions

- modules/cactus-web/src/Calendar/Calendar.tsx
- modules/cactus-web/src/Calendar/Grid.tsx
- modules/cactus-web/src/Calendar/Slider.tsx
https://repayonline.atlassian.net/browse/CACTUS-454
Not sure why I had to change the hook in Grid to get the DateInput's focus-on-open to work. The render order should be the same, but I guess _something_ changed somehow. 🤷
IE isn't supported, but since I assume swiping is mostly for mobile I doubt that's a big deal. The other thing that requires attention is the "residual", where it keeps sliding after you let go if you move fast. I played around with numbers and functions, but didn't really get it to where it feels completely natural to me; if any of you have ideas or suggestions, I'd be happy to hear them. It might just be because I was using a mouse and not an actual touchscreen.
> CACTUS-454: add swipe functionality to Calendar

- modules/cactus-web/src/Pagination/Pagination.tsx
[CACTUS-780](https://repayonline.atlassian.net/browse/CACTUS-780)
Thread of the [issue](https://repay.slack.com/archives/CABGTU4S3/p1653493399955329)
> CACTUS-780 :: MIN-ITEMS fix

- modules/cactus-web/src/Calendar/Calendar.tsx
- modules/cactus-web/src/Calendar/Grid.tsx
- modules/cactus-web/src/Calendar/Slider.tsx
> Revert "CACTUS-454: add swipe functionality to Calendar"

- modules/cactus-web/src/Header/Header.test.tsx
- modules/cactus-web/src/Header/Header.tsx
Ticket & UAT: https://repayonline.atlassian.net/browse/CACTUS-927
> CACTUS-927 :: Render H1 in Header.Title

- modules/cactus-web/src/Layout/grid.ts
[CACTUS-922](https://repayonline.atlassian.net/browse/CACTUS-922)
> CACTUS-922 :: Footer Hidden in layout 

- modules/cactus-icons/.storybook/main.js
- modules/cactus-icons/package.json
- modules/cactus-web/.storybook/main.js
- modules/cactus-web/cactus-addon/controls.js
- modules/cactus-web/package.json
- package.json
- yarn.lock
Ticket & UAT: https://repayonline.atlassian.net/browse/CACTUS-955
> CACTUS-955 :: Storybook IE11 Issue

- .github/workflows/snyk-scan.yml
https://repayonline.atlassian.net/browse/CACTUS-958
Making the PR took longer than the actual change...
> CACTUS-958: Snyk to scan master

- .github/workflows/master-workflow.yml
> CACTUS-966:: Fix

- .github/workflows/master-workflow.yml
[CACTUS-966](https://repayonline.atlassian.net/browse/CACTUS-966) 
**Plays Van Hallen's Sweet Victory**
> CACTUS-966 :: Docs Publish 

- modules/cactus-web/src/MenuBar/MenuBar.story.tsx
- modules/cactus-web/src/MenuBar/MenuBar.tsx
Ticket & UAT: https://repayonline.atlassian.net/browse/CACTUS-1034
> CACTUS-1034 :: MenuBar Active Styles

- modules/cactus-web/src/Notification/Notification.tsx
[CACTUS-1057](https://repayonline.atlassian.net/browse/CACTUS-1057)
🙃
> CACTUS-1057 :: Fix Notification Provider

- modules/cactus-web/src/Modal/Modal.tsx
Ticket & UAT: [CACTUS-1075](https://repayonline.atlassian.net/browse/CACTUS-1075)
Tested this on Channels and it works.
> cactus-1075:: modal-bugfix-1

- modules/cactus-web/src/Tooltip/Tooltip.mdx
- modules/cactus-web/src/Tooltip/Tooltip.story.tsx
- modules/cactus-web/src/Tooltip/Tooltip.test.tsx
- modules/cactus-web/src/Tooltip/Tooltip.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-903
UAT:
- Try adding the tooltip position function that I left in the mdx file to the tooltip in the storybook docs and see how it behaves.
> Cactus 903  tooltip remove position wrapper

- docs/Forms/API Documentation.md
- examples/mock-ebpp/src/containers/rules.tsx
- examples/mock-ebpp/tests/rules-integration.test.ts
- modules/cactus-form/src/FormSpy.tsx
- modules/cactus-form/src/SubmitButton.ts
- modules/cactus-form/src/index.ts
- modules/cactus-form/tests/__snapshots__/exports.test.ts.snap
- modules/cactus-form/tests/form.test.tsx
Ticket & UAT: https://repayonline.atlassian.net/browse/CACTUS-1092
> CACTUS-1092 :: SubmitButton

- docs/Forms/API Documentation.md
- examples/mock-ebpp/src/containers/rules.tsx
- examples/mock-ebpp/tests/rules-integration.test.ts
- examples/mock-ebpp/types.ts
- modules/cactus-form/src/FieldArray.ts
- modules/cactus-form/src/config.ts
- modules/cactus-form/src/index.ts
- modules/cactus-form/tests/__snapshots__/exports.test.ts.snap
- modules/cactus-form/tests/form.test.tsx
https://repayonline.atlassian.net/browse/CACTUS-919
I've gone over this situation several times in the last couple of years, since we first re-wrote the rules form, and I'm no happier now with this solution than I was then but I still can't think of any way to track changes besides putting a new key property on the objects. The worst part is this doesn't even fully address the problem the rules form was having, but I've never been able to come up with a good solution for such massive forms, or at least, not within the framework of final-form.
> CACTUS-919 FieldArray

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
[Ticket and UAT](https://repayonline.atlassian.net/browse/CACTUS-1145)
> cactus 1145 - .vscode config

- modules/cactus-web/src/DateInput/DateInput.tsx
- modules/cactus-web/src/FileInput/FileInput.tsx
[Ticket & UAT](https://repayonline.atlassian.net/browse/CACTUS-1133)
Both Snyk and SonarQube aren't working properly right now and haven't been updated in a couple of months. I don't know much about the Snyk setup, but I _do_ know enough about how SonarQube works to get around the problem and get an updated list of things to look at. Unfortunately, this means that there aren't any security-related dependency updates for this round, since those come from Snyk. We have tickets to fix both of them, so next time we should have issues that are more current to work off of.
The changes here are in response to some code smells that were flagged by SonarQube, mainly due to functions exceeding the complexity threshold of 15 conditional branches per function. I split some logic out into separate …
> CACTUS-1133 :: Snyk/SonarQube Fixes

- yarn.lock
https://repayonline.atlassian.net/browse/RC-7100
> RC-7100 Upgrade vulnerable libs (as much as possible, anyway).
