modules/cactus-web/package.json, modules/cactus-web/src/Button/Button.tsx, modules/cactus-web/src/Button/__snapshots__/Button.test.tsx.snap, modules/cactus-web/src/TextButton/TextButton.story.tsx, modules/cactus-web/src/TextButton/TextButton.test.tsx, modules/cactus-web/src/TextButton/TextButton.tsx, modules/cactus-web/src/TextButton/__snapshots__/TextButton.test.tsx.snap
I branched off of the `icon-buttons` branch, so that should be reviewed and merged first. (#20)
I noticed that I didn't add a strikethrough on disabled buttons, so there's a commit in here to do that as well.
Text+Icon buttons didn't require a new component; you can just put an icon inside `TextButton` along with some text to achieve the effect, so I just added onto the `TextButton` stories/tests
=> feat(cactus-web): Text icon buttons

modules/cactus-web/src/IconButton/IconButton.story.tsx, modules/cactus-web/src/TextButton/TextButton.story.tsx, modules/cactus-web/src/TextButton/TextButton.tsx, modules/cactus-web/src/TextButton/__snapshots__/TextButton.test.tsx.snap
1. Fixed alignment for text+icon buttons
2. Fixed font weight on standard inverse text buttons. (I also found that 300 is *not* the default font weight, so I removed that so it would default correctly.)
3. Refactored icon button and text+icon button stories to include an icon dropdown just like the one in the icon module's story.
4. Fixed a bug in which the strikethrough would be replaced by an underline when hovering over a disabled text button.
=> fix(cactus-icons): text & text+icon button improvements

modules/cactus-web/src/CheckBox/CheckBox.story.tsx
Just adding a story showing that you can manage the `checked` prop on our checkbox
=> chore(cactus-web): Show how to manage checkbox state using props

modules/cactus-web/package.json, modules/cactus-web/src/CheckBox/CheckBox.test.tsx, yarn.lock
Updating our checkbox tests to use `user-event`, which recently published a fix for the issue of triggering events even when the checkbox is disabled
=> test(cactus-web): Add tests for disabled checkboxes

modules/cactus-web/src/Label/__snapshots__/Label.test.tsx.snap, modules/cactus-web/src/Toggle/Toggle.tsx, modules/cactus-web/src/Toggle/__snapshots__/Toggle.test.tsx.snap
I noticed that the color was off, too, so that's fixed as well. Other than that, I just had to resize the icons and shift them slightly to adhere to the style guide.
=> fix(cactus-web): Size & position toggle icons appropriately

modules/cactus-web/src/Toggle/Toggle.tsx, modules/cactus-web/src/Toggle/__snapshots__/Toggle.test.tsx.snap
While working on the case study for shadows, I noticed that, if a toggle is placed inside a `<form>` tag, it will try to submit the form when clicked. 🤯
By adding `type="button"` to the toggle, that issue is prevented.
=> fix(cactus-web): Add button type to toggle

modules/cactus-web/src/CheckBox/CheckBox.tsx, modules/cactus-web/src/CheckBox/__snapshots__/CheckBox.test.tsx.snap
I also realized that the checkmark SVG should still show even if the checkbox is disabled, so I fixed that.
=> feat(cactus-web): Add box shadow on focus for checkbox

modules/cactus-web/src/TextInput/TextInput.tsx, modules/cactus-web/src/TextInput/__snapshots__/TextInput.test.tsx.snap
Defined padding bottom and left on text input to ensure that the text is lined up correctly with the left side of the input
=> fix(cactus-web): Line up text on left side of input correctly

modules/cactus-fwk/package.json, modules/cactus-icons/package.json, modules/cactus-theme/package.json, modules/cactus-web/package.json
I've already deprecated the v1 packages on npm, these are the new versions that I will publish for these libraries except for cactus-fwk which has no changes since v0.2.0
=> chore(): deprecate v1 and revert to v0 publishes

modules/cactus-web/src/Button/Button.tsx, modules/cactus-web/src/Button/__snapshots__/Button.test.tsx.snap, modules/cactus-web/src/IconButton/IconButton.tsx, modules/cactus-web/src/IconButton/__snapshots__/IconButton.test.tsx.snap, modules/cactus-web/src/TextButton/TextButton.tsx, modules/cactus-web/src/TextButton/__snapshots__/TextButton.test.tsx.snap
Fixes the dotted line that shows up in Firefox only. We could, but shouldn't add this globally because it will force us to realize our own focus states where we remove these.
https://css-tricks.com/removing-the-dotted-outline/#article-header-id-3
=> fix(cactus-web): firefox dotted line on focus

modules/cactus-web/scripts/make-component.js, modules/cactus-web/src/Grid/Grid.test.tsx, modules/cactus-web/src/Grid/Grid.tsx, modules/cactus-web/src/Grid/__snapshots__/Grid.test.tsx.snap, modules/cactus-web/src/IconButton/IconButton.story.tsx, modules/cactus-web/src/IconButton/IconButton.tsx, modules/cactus-web/src/IconButton/__snapshots__/IconButton.test.tsx.snap
Alright, so I also added the `justify` prop to `Grid` and that will give the devs some more control over the content inside grids. I noticed that would be a nice feature when I was using the grid to lay out the new story for the icon buttons. Other than that this is the new icon button focus state that we talked about this morning
=> feat(cactus-web): Add new icon button focus state

modules/cactus-web/src/IconButton/IconButton.tsx, website/gatsby-config.js, website/package.json, website/src/components/Layout.tsx, website/src/components/Link.tsx, website/src/pages/design-system/icons.tsx, website/src/pages/design-system/language.tsx, website/src/pages/design-system/typography.tsx, website/src/pages/stories.tsx, yarn.lock
This finishes up converting the links on the documentation website and fixes markdown rendered links by accepting href as well as to. Also uses normal anchor tags for links outside of the site.
=> fix(docs): allow href for markdown rendering

modules/cactus-web/src/TextInputField/TextInputField.tsx, modules/cactus-web/src/TextInputField/__snapshots__/TextInputField.test.tsx.snap
Quick fix for `TextInputField`
=> fix(cactus-web): Don't pass margin props to inner input element

modules/cactus-web/src/Select/Select.tsx
When I was adding the select fields in channels, I noticed that we were getting some console errors when the query selector to find select options contained a url in its value. Turns out it was because of some special characters in the url (colon, slash, period). This PR just removes them, but if you want to replace them with something other than empty string I'm all for it.
=> fix(cactus-web): Remove special characters in select ids

modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/Tooltip/Tooltip.tsx, modules/cactus-web/src/Tooltip/__snapshots__/Tooltip.test.tsx.snap
When width was left to be auto-generated it was drifting from the initial value causing it to shrink like observed for whatever reason. By setting it explicitly to itself prevents this. 
Also set the default maxWidth to the minimum of `window.innerWidth` and `500` because no one needs a tooltip that's 1024 pixels wide.
=> fix(cactus-web): fix tooltip width drift

modules/cactus-web/src/Select/Select.tsx
By prefixing the option ids with the id of the select itself, it makes them unique enough to use `document.getElementById()` instead of `querySelector`. That way, we don't have to worry about special characters in the label or value. I tested this with all of the options I've found in channels that cause these console errors and this fix seemed to take care of the problem.
=> fix(cactus-web): Make select option ids unique enough to use getElementById

examples/standard/package.json, examples/standard/src/containers/Home.tsx, modules/cactus-web/src/Select/Select.story.tsx, modules/cactus-web/src/Select/Select.test.tsx, modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/SelectField/SelectField.story.tsx, modules/cactus-web/src/SelectField/SelectField.tsx
Two changes happening here:
1. We no longer get console errors when an empty options list is given to the select
2. We are allowing number values to be passed in `options`
Let me know if you have any questions!
=> fix(cactus-web): Allow Select to receive empty options & numbers

modules/cactus-web/src/FileInput/FileInput.tsx, modules/cactus-web/src/FileInput/__snapshots__/FileInput.test.tsx.snap, modules/cactus-web/src/FileInputField/FileInputField.tsx, modules/cactus-web/src/FileInputField/__snapshots__/FileInputField.test.tsx.snap
My main goal with this PR was to stop the file input from automatically growing to its parent width, but I also made sure the border was using the right color, since it was one shade too light. I also added some extra spacing between the file name and the close button
=> fix(cactus-web): Prevent file input from growing to 100% of parent width

modules/cactus-web/src/FileInput/FileInput.tsx, modules/cactus-web/src/FileInput/__snapshots__/FileInput.test.tsx.snap, modules/cactus-web/src/FileInputField/FileInputField.tsx, modules/cactus-web/src/FileInputField/__snapshots__/FileInputField.test.tsx.snap
There were 3 things that could be improved that I came across as I was adding the file input to channels:
1. Stop removing `data:` and `base64,` from the dataURL. We need to keep that to display images on the page sometimes. Best to leave any modification of that string up to the developer.
2. Make `accept` optional. This prop isn't required on a basic file input, so I don't want to make it required on this. Additionally, there are places in channels where we might shoot ourselves in the foot by restricting file types.
3. Pass the `name` prop to the hidden input and set the value of that input when files are dropped. This will ensure the values are set in the cases when we send the raw form data to the backend.
=> File input improvements

.circleci/config.yml, examples/mock-ebpp/.babelrc, examples/mock-ebpp/global.d.ts, examples/mock-ebpp/node.d.ts, examples/mock-ebpp/package.json, examples/mock-ebpp/tests/config/puppeteer-environment.js, examples/mock-ebpp/tests/config/setup.ts, examples/mock-ebpp/tests/config/teardown.ts, examples/mock-ebpp/tests/constants.ts, examples/mock-ebpp/tests/form-elements.test.ts, examples/mock-ebpp/tests/helpers/form-actions.ts, examples/mock-ebpp/tests/helpers/static-server.ts, examples/mock-ebpp/tests/helpers/wait.ts, examples/mock-ebpp/tsconfig.json, examples/mock-ebpp/types.ts, yarn.lock
Adds integration tests for our form elements to the mock-ebpp test app. Admittedly, these tests aren't as fleshed out as I'd like them to be, but I've been working on this for several days and I'd like to get at least this into the pipeline and get back to working on Channels, and this is at least a good starting point.
=> test(cactus-web): Add integration tests to our test app

modules/cactus-web/src/Toggle/Toggle.tsx, modules/cactus-web/src/Toggle/__snapshots__/Toggle.test.tsx.snap, modules/cactus-web/src/ToggleField/ToggleField.tsx, modules/cactus-web/src/ToggleField/__snapshots__/ToggleField.test.tsx.snap
Adjusts toggle to fit Mariana's new designs. The only difference is that, after reviewing her designs, Aaron and Allen decided that they liked the idea of using red as the "off" color. I cleared that idea with Mariana, who actually seemed to like it quite a bit, and implemented that here. 
I also fixed a bug/oversight with the `ToggleField` where the cursor on the label wasn't being changed when the toggle is disabled.
Some bonus awesome-ness: After fiddling around with the alignment on the `ToggleField`, I managed to get the label and toggle to align how I want them to across Chrome, Firefox, Safari, AND IE. Phew!
=> refactor(cactus-web): New toggle styles

modules/cactus-theme/index.ts, modules/cactus-web/src/Button/Button.story.tsx, modules/cactus-web/src/Button/Button.test.tsx, modules/cactus-web/src/Button/Button.tsx, modules/cactus-web/src/Button/__snapshots__/Button.test.tsx.snap, modules/cactus-web/src/IconButton/IconButton.story.tsx, modules/cactus-web/src/IconButton/IconButton.test.tsx, modules/cactus-web/src/IconButton/IconButton.tsx, modules/cactus-web/src/IconButton/__snapshots__/IconButton.test.tsx.snap
This adds the styles for the danger variants for `Button` and `IconButton`. We already have a danger variant for `TextButton` implemented.
I didn't get any designs for the inverse versions of these variants,  but I just tried to follow the same patterns we've done for the other ones. If we end up using them later on down the line, I'm sure Mariana will stub out some designs for them.
I also fixed a bug in the `IconButton` story that was caused by trying to render all values inside `icons`. Apparently, the last value is a parse function and not an icon, so I sliced it out before rendering.
=> Danger Buttons

modules/cactus-web/src/Select/Select.test.tsx, modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/StyleProvider/StyleProvider.tsx, modules/cactus-web/src/helpers/constants.ts
Keeps multiselect open when you click options, adds mobile version of the select's dropdown. Honestly, I'm not very happy with the way I ended up having to do the fade in/out on the dropdown, but I've been trying anything I can think of for days now and there just doesn't seem to be a good way to make the gradients appear only when you have somewhere to scroll, so I had to just add some extra vertical padding. I also don't think we can test this outside integration tests since we don't have a viewport for the unit tests. Anyway, I'm open to any feedback on this so let me know what you think.
=> feat(cactus-web): Add more mobile optimized select dropdown

modules/cactus-web/src/Select/Select.test.tsx, modules/cactus-web/src/Select/Select.tsx
Fixes that weird issue where values were displayed in reverse order if their corresponding options were generated from the values
=> Reverse Values Fix

modules/cactus-web/src/Select/Select.tsx
When I built the combobox, I looked at the ids on the options to determine if the id contained "create", in which case I gave it the "create" `data-role`. However, option ids are generated in part using the option's label, so this breaks if the option contains the string "create".  /facepalm
This fixes that issue, though, and I already tested it locally on channels
=> fix(cactus-web): Fix how we decide to make an option the create option

modules/cactus-web/src/Select/Select.test.tsx, modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/Select/__snapshots__/Select.test.tsx.snap, modules/cactus-web/src/SelectField/__snapshots__/SelectField.test.tsx.snap
A few weeks ago we talked about disabling the select and providing a descriptive placeholder to explain why it's disabled so I decided to get that knocked out real quick. Pretty simple
=> Handle No Options in Select

examples/mock-ebpp/package.json, examples/standard/package.json, examples/theme-components/package.json, modules/cactus-web/src/Accordion/Accordion.story.tsx, modules/cactus-web/src/Accordion/Accordion.test.tsx, modules/cactus-web/src/Accordion/Accordion.tsx, modules/cactus-web/src/Accordion/__snapshots__/Accordion.test.tsx.snap, website/package.json, yarn.lock
Allows devs to initially render an open accordion using the `open` prop.
To do this, I had to refactor the structure of the `managedAccordions` ref that I added in my last PR, and use that for both focus management (same as before) and for managing whether or not accordions are open (new behavior). Previously, I was using the `useState` hook in the provider to manage whether or not the accordions were open, but now I need that information to be available from the first render. 
Let me know if you have any questions/comments!
=> feat(cactus-web): Allow user to initially render accordions open

modules/cactus-web/src/helpers/dates.ts, modules/cactus-web/tests/dates.test.ts
JS Date objects assume the year is 1900s if provided value is less than 100,
therefore we need to use setFullUTCYear to not only set the full year but
also prevent the date object from changing through timezones.
=> fix(cactus-web): Date objects to have correct year when less than 100

modules/cactus-web/src/DateInput/DateInput.story.tsx, modules/cactus-web/src/helpers/dates.ts
This appears to be caused by the minor time adjustments which happen over large amounts of time so when changing the years it will adjust the time by some minutes. To account for this, I generate the date and then set all of the values directly.
=> fix(cactus-web): date input changes time with large year changes

examples/mock-ebpp/src/containers/faq.tsx, examples/mock-ebpp/tests/helpers/actions.ts, modules/cactus-web/src/Accordion/Accordion.mdx, modules/cactus-web/src/Accordion/Accordion.story.tsx, modules/cactus-web/src/Accordion/Accordion.test.tsx, modules/cactus-web/src/Accordion/Accordion.tsx, modules/cactus-web/src/Accordion/__snapshots__/Accordion.test.tsx.snap, modules/cactus-web/src/IconButton/IconButton.tsx
Converted the accordion headers to `div` rather than `button` so we can include whatever kinds of headers we want as children. This is a breaking change because, previously, the accordion headers automatically had h3 styles, whereas now you must explicitly render your accordion header with whatever text styles you want
=> fix(cactus-web): Provide more space for elements in accordion header

modules/cactus-web/src/helpers/dates.ts, modules/cactus-web/tests/dates.test.ts
Timezones are slightly different in Firefox vs Safari/Chrome so in order to prevent the time slippage we need to just let the UTC time be different in different browsers ☹️
=> fix(cactus-web): firefox differences in timezone offsets

modules/cactus-web/src/DateInput/DateInput.tsx, modules/cactus-web/src/helpers/dates.ts, modules/cactus-web/tests/dates.test.ts
This fixes the the issue where DateInput would incorrectly parse provided date strings when no format was provided as a prop. This also updates the default datetime format to conform more strictly to the ISO8601 format with a `T` between the date and time sections. I.e. `YYYY-MM-ddTHH:mm`
BREAKING: the default datetime format for the DateInput and DateInputField
now includes a T separator. No change is necessary if already using an ISO8601
date parser.
=> Use default date formats

modules/cactus-web/src/Accordion/Accordion.test.tsx, modules/cactus-web/src/Accordion/Accordion.tsx
Quick bug fix to restrict the accordion from toggling its open/closed state based on what target was clicked.
=> fix(cactus-web): Fix buttons in header toggling accordion

docs/Internationalization/API Documentation.md, docs/Internationalization/Getting Started.md, examples/mock-ebpp/tests/integration.test.ts, examples/standard/src/containers/Snacks.tsx, examples/standard/src/index.tsx, examples/standard/src/locales/en/carrots.js, examples/standard/src/locales/en/chips.js, examples/standard/src/locales/en/coffee.js, examples/standard/src/locales/en/cookies.js, examples/standard/src/locales/en/fruit.js, examples/standard/src/locales/en/snacks.js, examples/standard/src/locales/en/terms.js, examples/standard/src/locales/es/carrots.js, examples/standard/src/locales/es/chips.js, examples/standard/src/locales/es/coffee.js, examples/standard/src/locales/es/cookies.js, examples/standard/src/locales/es/fruit.js, examples/standard/src/locales/es/snacks.js, examples/standard/src/locales/es/terms.js, modules/cactus-i18n/src/BaseI18nController.ts, modules/cactus-i18n/src/Components.tsx, modules/cactus-i18n/tests/i18n.test.tsx
* docs(examples): use more idiomatic fluent translations
* feat(cactus-i18n): merge sections into a single bundle per language
* feat(cactus-i18n): only load supported languages
* feat(cactus-i18n): make i18n library platform agnostic
BREAKING: 
* all keys in a given section must be prefixed with the pattern:
`<section>__<id>` so that there are no conflicts when merging the resources into
the single bundle.
* The I18nProvider will no longer use navigator.language internally to
ensure cross platform usage. Therefore, any DOM usage should provide the
navigator.language as the initial value for I18nProvider lang prop.
=> I18n Upgrades

modules/cactus-i18n/src/BaseI18nController.ts, modules/cactus-i18n/tests/i18n.test.tsx
Will allow disabling the isolating characters `U+2068` and `U+2069` in Windows until it has support.
=> feat(cactus-i18n): allow choosing to use isolating char

.github/workflows/continuous-integration.yml, modules/cactus-i18n/src/BaseI18nController.ts, modules/cactus-i18n/src/Components.tsx, modules/cactus-i18n/src/hooks.ts, modules/cactus-i18n/tests/i18n.test.tsx
* removes all logging when not in debug mode
* allows extra properties to be passed via `I18nSection` to the controller.load function
* allows adding dependencies to an `I18nSection`
[CACTUS-232]
[CACTUS-233]
[CACTUS-232]: https://repayonline.atlassian.net/browse/CACTUS-232
[CACTUS-233]: https://repayonline.atlassian.net/browse/CACTUS-233
=> feat(cactus-i18n): restrict logging to debugMode only

modules/cactus-i18n/package.json, modules/cactus-i18n/src/BaseI18nController.ts, yarn.lock
This fixes a bug in IE11 where pluralized translations aren't working. Need to get this merged ASAP
=> fix(cactus-i18n): Add plural rules polyfill to support IE11

examples/mock-ebpp/tests/integration.test.ts
I'm not 100% sure that this will fix the problem, but I did manage to get the integration tests to pass four times in a row with this timeout. We'll have to see how things go with this over the next couple of weeks or so.
=> test(): Jack up jest timeout for integration tests

modules/cactus-theme/src/theme.ts, modules/cactus-theme/tests/theme.test.ts, modules/cactus-web/cactus-addon/register.jsx, modules/cactus-web/package.json
I added the following new options to the theme generator:
- border
- shape
- font
- boxShadows
Each of these are optional, so if you don't pass any values for them, they'll default to the values for the cactus theme. For the fonts, I wanted to make sure we still have fallback fonts available, so I basically just made sure to put whatever font is chosen at the front of the comma-separated list of fonts. That way, the chosen font will be the first font the browser looks for, but if it's not there, we can still fall back to one of the other fonts we have set.
These changes are a little weird to test since these properties aren't actually being used yet, but if you want to do some local testing just for sanity's sake, you can add some console logs in a component's css like so:
```
${p => { …
```
=> Extend Theme Generator Options

.gitignore, modules/cactus-web/src/Modal/Modal.mdx, modules/cactus-web/src/Modal/Modal.story.tsx, modules/cactus-web/src/Modal/Modal.tsx, modules/cactus-web/src/Modal/__snapshots__/Modal.test.tsx.snap
https://repayonline.atlassian.net/browse/CACTUS-259
The main issue, it turns out, was simply that it's a bad idea to specify the height of the modal. It works much better if the modal auto-sizes, and then the user can scroll the entire page if it's too tall: most of the changes were to make the modal look better when there's no height specified. Still, I didn't want to remove the option entirely, so I also added overflow scrollbars. That's really not recommended, though, since the scrollbars turn the nice rounded corners into right angles, and I don't know of any way to prevent that.
There are a quite a few changes here:
* Updated Storybook so there is no default height.
* Added `nowrap` to the primary modal content, so it will always be rendered in a single column.
* Hide the `children` …
=> CACTUS-259 Fix Modal Render Issue

modules/cactus-i18n/src/index.ts, modules/cactus-i18n/tests/__snapshots__/exports.test.ts.snap
The i18nContext can now be imoorted from @repay/cactus-i18n like import {i18nContext} from
'@repay/cactus-i18n'
[CACTUS-254]
[CACTUS-254]: https://repayonline.atlassian.net/browse/CACTUS-254
=> feat(cactus-i18n): i18nContext importable from @repay/cactus-i18n

examples/mock-ebpp/package.json, examples/standard/package.json, examples/theme-components/package.json, modules/cactus-icons/package.json, modules/cactus-web/package.json, website/package.json, yarn.lock
Since `@repay/cactus-theme` was published with `v0.5.0`, all the `^0.4.x` dependencies in other modules need to be changed to make sure we keep pulling in the latest version.
FYI, I did not add a scope to the commit that bumped the dependency in the icons lib.  It's just a dev dependency that affects Storybook, not the package code itself, so I don't think it should be included in the Changelog.
=> Update cactus-theme dependencies

modules/cactus-web/src/AccessibleField/AccessibleField.tsx, modules/cactus-web/src/DateInputField/__snapshots__/DateInputField.test.tsx.snap, modules/cactus-web/src/FileInput/FileInput.tsx, modules/cactus-web/src/FileInput/__snapshots__/FileInput.test.tsx.snap, modules/cactus-web/src/FileInputField/__snapshots__/FileInputField.test.tsx.snap, modules/cactus-web/src/SelectField/__snapshots__/SelectField.test.tsx.snap, modules/cactus-web/src/StatusMessage/StatusMessage.tsx, modules/cactus-web/src/TextAreaField/__snapshots__/TextAreaField.test.tsx.snap, modules/cactus-web/src/TextInputField/__snapshots__/TextInputField.test.tsx.snap
Ticket: https://repayonline.atlassian.net/browse/CACTUS-255
I'm sure I missed something, but hopefully I got everything in there.  When testing, I'd be sure to go into all of the `BlahBlahField` components (i.e. TextInputField, SelectField, ...) with the exception of `CheckboxField` and `RadioButtonField`.
Also, I ended up making some changes to the `FileInput` component, as the style guide did not have the `StatusMessage` taking up 100% of the width.  This required adjusting the placement of the refresh icon.  I think it looks fine if the message is on one line, but I'm not sure about two lines.  However, I'm unsure how to style it any differently.
=> CACTUS-255 :: StatusMessage Style Update

examples/mock-ebpp/package.json, examples/standard/package.json, examples/theme-components/package.json, modules/cactus-fwk/package.json, modules/cactus-i18n/package.json, modules/cactus-icons/package.json, modules/cactus-theme/package.json, modules/cactus-web/package.json, yarn.lock
I'd make sure `yarn build` still works at the Cactus root.  You could then try running `yarn w mock-ebpp start` to ensure that the example apps still work.
=> Upgrade @repay/scripts to 0.5.0 

examples/mock-ebpp/src/api.tsx, examples/mock-ebpp/src/containers/account.tsx, examples/mock-ebpp/src/containers/accounts.tsx, examples/mock-ebpp/src/index.tsx, examples/mock-ebpp/tests/account-integration.test.ts, examples/standard/src/App.tsx, examples/standard/src/index.tsx, examples/standard/src/locales/en/global.js, examples/standard/src/locales/es/global.js, examples/standard/tests/i18n-integration.test.ts, modules/cactus-web/src/MenuButton/MenuButton.tsx, modules/cactus-web/src/SplitButton/SplitButton.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-273
Working on this made a bug that we hadn't noticed before pretty obvious: the background on the dropdown in both of these components was transparent! I guess we just hadn't rendered them on anything but a white background. So that should be fixed now.
I swapped the language select in `examples/standard` to the `MenuButton` & updated the integration test to work with that component
For this one, I added a column to the accounts table in `examples/mock-ebpp` and filled it up with SplitButtons with and some basic actions: view the account page or delete the account. Obviously the account page I added is very basic but hey, it's just an example app 🤷‍♂️ 
Not really much to test here, but you should probably check out this branch and …
=> CACTUS-273 :: SplitButton & MenuButton Integration Tests

modules/cactus-web/src/MenuButton/MenuButton.tsx, modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/SplitButton/SplitButton.tsx
Text overflow now breaks instead of overflowing. Fixed MenuButton dropdown showing up behind text
[CACTUS-274]
[CACTUS-274]: https://repayonline.atlassian.net/browse/CACTUS-274
=> style(cactus-web): fixed text overflow in dropdowns

modules/cactus-web/package.json
Ticket: https://repayonline.atlassian.net/browse/CACTUS-272
So obviously this required very little actual changes to get it to work. Most of my time was spent understanding how the stories are built/published & then doing research to figure out how to get the custom addon to be built with everything else.
The thread that ultimately led to me figuring this out can be found here: https://github.com/storybookjs/storybook/issues/6413
Bring up the published storybooks for `cactus-web` (https://repaygithub.github.io/cactus/stories/cactus-web/?path=/story/accessiblefield--basic-usage) and notice that the "Cactus Theme" tab is now available in the bottom section. Play around with the theme on some components that make use of those theme properties & make sure they're still being adjusted w/ the …
=> CACTUS-272 :: Publish Theme Addon With Storybooks

docs/Framework/API/Error Boundary.md, docs/Framework/API/README.md, docs/Framework/README.md
Ticket: https://repayonline.atlassian.net/browse/CACTUS-191
Not much to test.  Just run `yarn docs start` and make sure all the links to the Error Boundary page work (and that the docs were updated as in the ticket).
=> Fix examples of error view component in error boundaries

.eslintrc, package.json, yarn.lock
https://repayonline.atlassian.net/browse/CACTUS-283
Companion to https://github.com/repaygithub/ui-tools/pull/40.
To test, just run `yarn install` and then `yarn fmt` or `yarn lint`. You can try changing some files to introduce formatting errors, and the linter should catch them or put them right back how they were.
=> CACTUS-283 Upgrade eslint

examples/mock-ebpp/package.json, examples/standard/package.json, examples/theme-components/package.json, website/package.json
The release left the build broken due to some dependency issues with our example apps.
=> Ooops, I broke the build

modules/cactus-web/src/Button/Button.tsx, modules/cactus-web/src/Button/__snapshots__/Button.test.tsx.snap, modules/cactus-web/src/ConfirmModal/__snapshots__/ConfirmModal.test.tsx.snap
See
https://stackoverflow.com/questions/30176560/css-after-pseudo-element-doesnt-work-inside-button-in-any-ie-version
Ticket and testing: https://repayonline.atlassian.net/browse/CACTUS-304
=> Fix focus outline bug for Button in IE11

modules/cactus-web/src/Accordion/Accordion.tsx, modules/cactus-web/src/Accordion/__snapshots__/Accordion.test.tsx.snap, modules/cactus-web/src/Alert/Alert.tsx, modules/cactus-web/src/Card/Card.tsx, modules/cactus-web/src/Card/__snapshots__/Card.test.tsx.snap, modules/cactus-web/src/CheckBox/CheckBox.tsx, modules/cactus-web/src/CheckBox/__snapshots__/CheckBox.test.tsx.snap, modules/cactus-web/src/CheckBoxField/__snapshots__/CheckBoxField.test.tsx.snap, modules/cactus-web/src/DataGrid/__snapshots__/DataGrid.test.tsx.snap, modules/cactus-web/src/DateInput/DateInput.tsx, modules/cactus-web/src/MenuButton/MenuButton.tsx, modules/cactus-web/src/Modal/Modal.tsx, modules/cactus-web/src/RadioButton/RadioButton.tsx, modules/cactus-web/src/RadioButton/__snapshots__/RadioButton.test.tsx.snap, modules/cactus-web/src/RadioButtonField/__snapshots__/RadioButtonField.test.tsx.snap, modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/SplitButton/SplitButton.tsx, modules/cactus-web/src/StepAvatar/StepAvatar.tsx, modules/cactus-web/src/StepAvatar/__snapshots__/StepAvatar.test.tsx.snap, modules/cactus-web/src/Toggle/Toggle.tsx, modules/cactus-web/src/Toggle/__snapshots__/Toggle.test.tsx.snap, modules/cactus-web/src/ToggleField/__snapshots__/ToggleField.test.tsx.snap, modules/cactus-web/src/Tooltip/Tooltip.tsx, modules/cactus-web/src/Tooltip/__snapshots__/Tooltip.test.tsx.snap
Ticket: https://repayonline.atlassian.net/browse/CACTUS-294
View the following components & compare them to what's shown & described in the style guide:
- Accordion (Outline Variant)
- Alert
- Card
- DateInput
- MenuButton
- Modal
- RadioButton (focus)
- Select (dropdown)
- SplitButton
- StepAvatar (in process)
- Toggle (focus)
- Tooltip
Note that there may still be a typo in the Figma style guide that says the `Select` should use the `S2` shadow, when it really is supposed to use `S1`.
=> refactor(cactus-web): Standardize box shadows using boxShadow helper

website/src/pages/design-system/shared-styles.tsx
We don't use a mini breakpoint, so this just removes that from the docs
=> Remove mini breakpoint from docs

examples/mock-ebpp/package.json, examples/standard/package.json, examples/theme-components/package.json, modules/cactus-fwk/package.json, modules/cactus-i18n/package.json, modules/cactus-icons/package.json, modules/cactus-theme/package.json, modules/cactus-web/package.json, yarn.lock
The next phase of upgrading the recently release `ui-tools` packages.
1. Run `yarn cleanup && yarn build` to make sure everything builds
2. Run `yarn web start` to make sure Storybook starts normally and looks normal.
3. Run `yarn w standard start` to build/run the standard example app.
4. Check out the standard app in Chrome to make sure everything looks good.
5. Check out the standard app in IE.
=> CACTUS-311 :: Upgrade @repay/babel-preset and @repay/scripts

docs/Internationalization/API Documentation.md, modules/cactus-i18n/package.json, modules/cactus-i18n/src/BaseI18nController.ts, modules/cactus-i18n/src/Components.tsx, modules/cactus-i18n/src/hooks.ts, yarn.lock
It appears there weren't any breaking changes introduced by Fluent.  The only thing I had to do was make some TypeScript changes.
To test, just fire up the `standard` example app and make sure everything works.  You should also do this in IE11 via BrowserStack.
=> CACTUS-311 :: Fluent Upgrades

modules/cactus-web/src/SplitButton/SplitButton.tsx, modules/cactus-web/src/SplitButton/__snapshots__/SplitButton.test.tsx.snap
Ticket and UAT: https://repayonline.atlassian.net/browse/CACTUS-324
Not too much to this.  Calling `setState` for a parent component while in a separate render function was causing the issue.  The solution was just to lift the `ReachMenu` component higher in the hierarchy so that we didn't need to keep `isOpen` in state.
=> Get rid of console warning triggered by SplitButton

modules/cactus-web/src/AccessibleField/AccessibleField.test.tsx, modules/cactus-web/src/AccessibleField/AccessibleField.tsx, modules/cactus-web/src/AccessibleField/__snapshots__/AccessibleField.test.tsx.snap, modules/cactus-web/src/CheckBoxField/CheckBoxField.tsx, modules/cactus-web/src/DateInputField/DateInputField.tsx, modules/cactus-web/src/FileInputField/FileInputField.tsx, modules/cactus-web/src/Label/Label.tsx, modules/cactus-web/src/RadioButtonField/RadioButtonField.tsx, modules/cactus-web/src/SelectField/SelectField.tsx, modules/cactus-web/src/TextAreaField/TextAreaField.tsx, modules/cactus-web/src/TextInputField/TextInputField.tsx
All usages of `Label` already accepted JSX, but while I was double-checking that I figured I'd standardize the usages & types. I also added some tests that cover the JSX case.
I'm planning on removing mapping types (`Pick`, `Omit`) where possible, and reducing nesting in others, for a couple of reasons:
- It improves readability of type errors, because `Pick`s can get pretty long, and `Omit`s even longer.
- While I was testing something, I found that running `Pick<React.ComponentProps<typeof Component>, 'some' | 'fields'>` changed optional fields to required. That's a pretty edge-case quirk that doesn't apply to simple types & interfaces, so I figured it would be best to simplify where possible.
Along with that, I'm changing `Omit` references from the one in our code to the builtin Omit, …
=> CACTUS-267: Label

modules/cactus-web/src/AccessibleField/AccessibleField.test.tsx, modules/cactus-web/src/AccessibleField/AccessibleField.tsx, modules/cactus-web/src/AccessibleField/__snapshots__/AccessibleField.test.tsx.snap, modules/cactus-web/src/FileInputField/FileInputField.tsx, modules/cactus-web/src/Tooltip/Tooltip.story.tsx, modules/cactus-web/src/Tooltip/Tooltip.tsx
Make `Tooltip` accept JSX; stop ignoring `position` prop. Thanks to the change I made previously with `FieldProps`, the change to the prop type in `AccessibleField` is propagated to all the components that use it. There was quite a bit of unused/unnecessary complexity in the types in that file.
BREAKING CHANGE: Removed unused props from `Tooltip`; the component's behavior is unchanged so it shouldn't break anything functionally, but the type signature is different so it could break Typescript builds. As a result, I had to remove the `children` from the `Tooltip` stories.
(Note that if I were designing the interface, I would have made the `children` be the content of the tooltip, and had an optional prop for changing the icon.)
=> CACTUS-267: Tooltip

modules/cactus-web/src/AccessibleField/AccessibleField.test.tsx, modules/cactus-web/src/AccessibleField/AccessibleField.tsx, modules/cactus-web/src/AccessibleField/__snapshots__/AccessibleField.test.tsx.snap, modules/cactus-web/src/Accordion/Accordion.tsx, modules/cactus-web/src/Alert/Alert.tsx, modules/cactus-web/src/Breadcrumb/Breadcrumb.story.tsx, modules/cactus-web/src/Breadcrumb/Breadcrumb.tsx, modules/cactus-web/src/Button/Button.tsx, modules/cactus-web/src/CheckBox/CheckBox.tsx, modules/cactus-web/src/ConfirmModal/ConfirmModal.story.tsx, modules/cactus-web/src/ConfirmModal/ConfirmModal.tsx, modules/cactus-web/src/FileInput/FileInput.tsx, modules/cactus-web/src/StatusMessage/StatusMessage.tsx, modules/cactus-web/src/TextArea/TextArea.story.tsx, modules/cactus-web/src/TextArea/TextArea.tsx
Most of the other changes are removing redundant props definitions & removing invalid props (mostly `ref` from components that don't actually support refs; I didn't consider this a breaking change because even though Typescript would allow the ref, React would complain about it). One breaking change on ConfirmModal, removing an unused prop that was part of the original modal design, but should have been removed when we made the split.
=> CACTUS-267: StatusMessage, BreadCrumb, & ConfirmModal

modules/cactus-web/src/DataGrid/DataGrid.test.tsx, modules/cactus-web/src/DataGrid/DataGrid.tsx, modules/cactus-web/src/DataGrid/__snapshots__/DataGrid.test.tsx.snap, modules/cactus-web/src/SplitButton/SplitButton.story.tsx, modules/cactus-web/src/SplitButton/SplitButton.tsx, modules/cactus-web/src/SplitButton/__snapshots__/SplitButton.test.tsx.snap
Ticket: https://repayonline.atlassian.net/browse/CACTUS-326
1. Open the "Fixed Width Container" storybook for the SplitButton and verify that the overflowing text in the main button is handled with an ellipsis.
2. Clean & build cactus-web with `yarn web cleanup && yarn web build`
3. Run the mock-ebpp example app with `yarn w mock-ebpp start`
4. Navigate to Accounts -> View All
5. Click on the "Date of Birth" header so that the arrow is displayed.
6. Shrink the page until you see the text in the header button wrap. Verify that the arrow stays to the right of the text and is centered vertically.
=> CACTUS-326 :: Overflow Errors

examples/mock-ebpp/src/components/MenuBar.tsx, modules/cactus-web/src/MenuBar/MenuBar.story.tsx, modules/cactus-web/src/MenuBar/MenuBar.test.tsx, modules/cactus-web/src/MenuBar/MenuBar.tsx, modules/cactus-web/src/MenuBar/__snapshots__/MenuBar.test.tsx.snap, modules/cactus-web/src/MenuBar/scroll.ts, modules/cactus-web/src/helpers/theme.ts
https://repayonline.atlassian.net/browse/CACTUS-290
I strongly recommend you look at the diff with whitespace ignored.
- Rather than the finicky scroll buttons, I just went with a builtin scrollbar. Maybe not the prettiest, but it's easy to implement _and_ use. (To be honest, I rather wish we did that for the original MenuBar styles as well...)
- For `mock-ebpp`, I basically hard-coded it to use the `large` screen size, so that the integration tests will still pass.
- ~I've noted that the scrolling behavior is weird when expanding/collapsing submenus on the sidebar (sometimes it'll scroll to the top for no apparent reason); I'll be looking into this.~ EDIT: Should be fixed now.
- I saw that two styles weren't quite right on IE: the focus outline and the overlay on `tiny` screen sizes. I …
=> CACTUS-290 Side-MenuBar

yarn.lock
This will address a security vulnerability.  This should only affect the docs website, so I'd just `yarn install` and then `yarn docs cleanup && yarn docs start` to test.
=> Upgrade decompress

yarn.lock
This will address a security vulnerability. This should only affect the docs website, so I'd just `yarn install` and then `yarn docs cleanup && yarn docs start` to test.
=> Upgrade bl

modules/cactus-web/src/Box/Box.mdx, modules/cactus-web/src/Box/Box.story.tsx, modules/cactus-web/src/Box/Box.test.tsx, modules/cactus-web/src/Box/Box.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-340
1. Open the basic usage Box story
2. Set `borderRadius` to "themed" using the knobs.
3. Change the theme shape and make sure the shape of the box changes with it.
4. Open the "Custom Border Radius Definitions" Box story. This story allows you to set custom objects for each of the border radius props.
5. Edit the values in the `borderRadius` object and make sure they're used and that they change with the theme.
6. Remove the object from `borderRadius` (replace the text in there with an empty object `{}`)
7. Set a custom border radius object for any/all of the individual border radii props and make sure those are working as well.
=> CACTUS-340 :: Box border-radius

docs/Components/API Documentation.md, examples/mock-ebpp/package.json, examples/mock-ebpp/src/containers/ui-config.tsx, examples/mock-ebpp/tests/helpers/actions.ts, yarn.lock
Ticket: https://repayonline.atlassian.net/browse/CACTUS-338
Like I mentioned in our meeting, I wanted to configure the form validation to use the `error` prop on our form elements. As I did this I found a couple of components that don't expose that prop:
- `RadioButtonField` - I think it would probably make the most sense to include `error`/`warning`/`success` props on the _group_ that Glen has been working on rather than individual radio button fields.
- `FileInputField` - This component provides ways for developers to render error messages when a file fails to upload, but not for things like when a user doesn't upload a file at all. I think we should add that feature and just display a status message below the box.
Let me know what you guys think about those suggestions.
This should …
=> CACTUS-338 :: Formik Example

modules/cactus-web/src/DataGrid/DataGrid.mdx, modules/cactus-web/src/DataGrid/DataGrid.story.tsx, modules/cactus-web/src/DataGrid/DataGrid.tsx, modules/cactus-web/src/Table/Table.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-348
To do this, I basically just took any extra props passed to `Column` or `DataColumn` and passed those to `Table.Cell`. Then, in `Table.Cell` I adjusted the CSS a bit so that we only set a `min-width` when `width` isn't passed. If it is passed, we just call the `width` function from Styled System.
The way I did this essentially gives developers the freedom to pass any extra props they want onto the table cells via the column props. Are you guys ok with that? It seemed like the right call to me.
1. Open the DataGrid Basic Usage story.
2. Set width values using the two new knobs: "Active Column Width" and "Action Column Width".
3. Make sure that the values you set are setting the column widths appropriately.
=> CACTUS-348 :: DataGrid Column Width

modules/cactus-web/cactus-addon/constants.js, modules/cactus-web/cactus-addon/index.tsx, modules/cactus-web/cactus-addon/register.jsx, modules/cactus-web/src/DataGrid/__snapshots__/DataGrid.test.tsx.snap, modules/cactus-web/src/Pagination/Pagination.tsx, modules/cactus-web/src/Pagination/__snapshots__/Pagination.test.tsx.snap
Ticket: https://repayonline.atlassian.net/browse/CACTUS-352
Pretty quick one here. The bug came up because the Channels team uses a CSS framework that applies `border-box` styles to all of their elements. For this reason, ~I left the `* { box-sizing: border-box }` style in the storybook CSS~ I added a field to the theme addon in storybook so that we can toggle the border-box styles easily at any time. That way, we can hopefully try to prevent similar issues from cropping up later on.
1. Bring up the DataGrid storybook and open the "Cactus Theme" addon tab. At the bottom, check the box to set all elements to `box-sizing: border-box`
2. Make sure there's no vertical scrollbar on the table itself. The pagination component should not be cut off.
2. If you want to test that the fix is _really_ …
=> CACTUS-352 :: DataGrid Scroll Bug

modules/cactus-web/src/TextInputField/TextInputField.story.tsx, modules/cactus-web/src/Tooltip/Tooltip.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-355
This was happening because `reach/tooltip` doesn't get the client rect for the trigger unless the mouse hovers over the tooltip icon. This wouldn't be a problem if the icon were always in the same place, but when the page is big enough to scroll, then the icon moves. My solution was to manage the ref on the trigger myself and call `getBoundingClientRect()` to pass that into our `cactusPosition` function.
1. Clean & rebuild `cactus-web` with `yarn web cleanup && yarn web build`
2. Run the mock-ebpp example app with `yarn w mock-ebpp start`
3. Open the UI Config form and make sure the tooltip comes up in the right spot when you trigger it by focusing on fields, even after you scroll on the page.
=> CACTUS-355 :: Tooltip Fix

modules/cactus-web/src/MenuButton/MenuButton.tsx, modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/SplitButton/SplitButton.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-345
I bumped up the percentage the `MenuButton` uses so that the dropdown could be at most 2x as large as the `MenuButton`, and I used that value for the `SplitButton` & `Select` as well.
Should we consider setting the maximum width the `Select`'s dropdown can grow past its trigger to something larger than 300px? I think 300px is probably fine for the other two, but for the `Select`, I think it'd be much more common to see them with width greater than 150px (the way it's written, if 150px < Select width < 300px, then the dropdown will grow past the select, but only up to 300px max). Maybe we could set the hard cap somewhere in the 400 - 500 pixel range for the `Select`?
1. Open the `MenuButton` storybook
2. Set the button's text to …
=> CACTUS-345 :: Dropdown Widths

examples/mock-ebpp/src/containers/ui-config.tsx, modules/cactus-web/src/AccessibleField/AccessibleField.story.tsx, modules/cactus-web/src/AccessibleField/AccessibleField.tsx, modules/cactus-web/src/DateInputField/DateInputField.story.tsx, modules/cactus-web/src/DateInputField/DateInputField.tsx, modules/cactus-web/src/FileInput/FileInput.tsx, modules/cactus-web/src/FileInputField/FileInputField.story.tsx, modules/cactus-web/src/FileInputField/FileInputField.test.tsx, modules/cactus-web/src/FileInputField/FileInputField.tsx, modules/cactus-web/src/FileInputField/__snapshots__/FileInputField.test.tsx.snap, modules/cactus-web/src/RadioGroup/RadioGroup.story.tsx, modules/cactus-web/src/RadioGroup/RadioGroup.tsx, modules/cactus-web/src/SelectField/SelectField.story.tsx, modules/cactus-web/src/SelectField/SelectField.tsx, modules/cactus-web/src/TextAreaField/TextAreaField.story.tsx, modules/cactus-web/src/TextAreaField/TextAreaField.tsx, modules/cactus-web/src/TextInputField/TextInputField.story.tsx, modules/cactus-web/src/TextInputField/TextInputField.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-356
Implemented that `autoTooltip` prop and exposed it on all relevant components, like we talked about in Slack.
1. Open the `FileInputField` storybook
2. Pass some text in for `success`, `warning`, and `error` and make sure the corresponding status messages are shown.
3. Test out the `autoTooltip` prop on `AccessibleField`, `RadioGroup`, `SelectField`, `TextInputField`, and `TextAreaField`.
=> CACTUS-356 :: FileInputField Validation Props

modules/cactus-web/package.json, website/gatsby-node.js, website/package.json, yarn.lock
Ticket: https://repayonline.atlassian.net/browse/CACTUS-373
To test, just run `yarn cleanup && yarn build && yarn docs start`.  Make sure that the live coding examples for the Cactus Web components still work.  I also published the docs from this branch, so you can verify that they work in the published website as well (https://repaygithub.github.io/cactus/).
=> CACTUS-373 :: Remove react-live from dependencies

modules/cactus-web/src/Box/Box.story.tsx, modules/cactus-web/src/Box/Box.test.tsx, modules/cactus-web/src/Box/Box.tsx, modules/cactus-web/src/Box/__snapshots__/Box.test.tsx.snap
Test:
- In Storybook, add content to the box that would overflow it's content
- Set the overflow, overflowX or overflowY prop to anything you want, and make sure it works as expected
[CACTUS-360]
[CACTUS-360]: https://repayonline.atlassian.net/browse/CACTUS-360
=> refactor(cactus-web): add overflow props to Box component

modules/cactus-web/src/ActionBar/ActionBar.tsx, modules/cactus-web/src/ActionBar/__snapshots__/ActionBar.test.tsx.snap, modules/cactus-web/src/Footer/Footer.tsx, modules/cactus-web/src/Footer/__snapshots__/Footer.test.tsx.snap, modules/cactus-web/src/Layout/Layout.tsx, modules/cactus-web/src/Layout/Sidebar.tsx, modules/cactus-web/src/MenuBar/MenuBar.tsx, modules/cactus-web/src/MenuBar/__snapshots__/MenuBar.test.tsx.snap, modules/cactus-web/src/helpers/theme.ts
Though this is not directly related to the ActionBar.Panel (CACTUS-346), it's something I wanted to do in my previous ticket to make future work (including the Panel) easier; I'm putting it up in a separate PR so as not to clutter up the ActionBar tickets, but this is something like CACTUS-333.5 or CACTUS-346.-5.
In order to decouple Sidebar, I changed Layout from directly referencing the Sidebar `styled-components` class, to referencing a generic CSS class that could be assigned to any component. This will also make it easier to cascade styles down the tree based on the current layout position.
While I was at it, I did a little refactoring of the `Footer`:
- Changed exported component to the new paradigm (not directly exposing styled component).
- Changed element from `div` to `footer`. …
=> Decouple Sidebar from Layout

modules/cactus-web/src/ActionBar/ActionBar.mdx, modules/cactus-web/src/ActionBar/ActionBar.story.tsx, modules/cactus-web/src/ActionBar/ActionBar.test.tsx, modules/cactus-web/src/ActionBar/ActionBar.tsx, modules/cactus-web/src/ActionBar/__snapshots__/ActionBar.test.tsx.snap, modules/cactus-web/src/Layout/Layout.story.tsx
Note that I didn't actually make id required, since it could still be used in the absence of ActionProvider.
=> CACTUS-378 ActionBar.Item key fix

modules/cactus-web/src/Table/Table.test.tsx, modules/cactus-web/src/Table/Table.tsx, modules/cactus-web/src/Table/__snapshots__/Table.test.tsx.snap
Check that the width prop is ignored in card view in both DataGrid and Table
[CACTUS-374]
[CACTUS-374]: https://repayonline.atlassian.net/browse/CACTUS-374
=> fix(cactus-web): ignore width on card view of table and Datagrid

examples/mock-ebpp/tests/helpers/actions.ts, examples/mock-ebpp/tests/ui-config-integration.test.ts, modules/cactus-web/.storybook/webpack.config.js, modules/cactus-web/src/Select/Select.tsx, yarn.lock
Ticket: https://repayonline.atlassian.net/browse/CACTUS-366
While testing the IE11 fix, I also found two quirks with the mobile "dropdown," so I just knocked those out here as well.  I've separated out the mobile fixes into their own commits if it helps to look at them that way.
1. In your normal browser, go through every story under `Select` and make sure everything works normally.
2. In IE11, repeat step 1.
3. You can test the mobile fix on your phone (see https://stackoverflow.com/questions/11005540/localhost-running-on-mac-can-i-view-it-on-my-android-phone for Android instructions...see Dhalton for iOS instructions).  Alternatively, you could use an emulator.  Or you could take my word for it 🤷
=> CACTUS-366 :: Fix IE11 ComboBox bug and mobile Select bugs

modules/cactus-web/src/StyleProvider/StyleProvider.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-287
I ended up having to `@ts-ignore` this for a couple of types in the theme that make it pretty difficult (maybe impossible?) to get the PropTypes to agree with TypeScript. The "problem" types I'm referring to are the ones associated with `fontSizes`, `mobileFontSizes`, and `iconSizes`. These attributes should all be set to arrays of numbers, but the arrays end up with some extra keys that are mapped to the array values, and the TypeScript types reflect this. However, I have not been able to find a way to define an array with those extra keys via PropTypes. I have custom validators set up to check the length and the types of the values set in the arrays, but I wasn't able to convince TS that that is acceptable. However, if anyone …
=> CACTUS-287 :: Theme PropTypes

examples/mock-ebpp/run-ete-tests.js, examples/standard/run-ete-tests.js
Tests hang for some reason when run in parallel, so this changes makes them run sequentially.  It's a major bummer, but we'll try to look into why this is happening later.
=> Fix BrowserStack Tests

modules/cactus-web/src/Table/Table.tsx, modules/cactus-web/src/Table/__snapshots__/Table.test.tsx.snap
See https://repay.slack.com/archives/CABGTU4S3/p1603824711026100
1. Open up the Table -> With Long Values story
2. Change one of the values provided to be a long word instead of text with a bunch of spaces.
3. Ensure that the text wraps and does not overflow the card
4. Open up the Table -> Layout story
5. Switch to the Card variant and play around with the Cell and Header text to be sure that everything is behaving as you'd expect for both short and long values.
=> Fix overflow for long words in table card view

modules/cactus-web/tests/storyshots.test.ts
This should hopefully reduce false positives.  See
https://github.com/americanexpress/jest-image-snapshot#recommendations-when-using-ssim-comparison
To test, simply run `yarn test:build` followed by `yarn test:docker` on your machine, and make sure they pass.
=> Change visual snapshot comparison method to SSIM

modules/cactus-web/src/AccessibleField/AccessibleField.test.tsx, modules/cactus-web/src/AccessibleField/AccessibleField.tsx, modules/cactus-web/src/CheckBoxGroup/CheckBoxGroup.tsx, modules/cactus-web/src/CheckBoxGroup/__snapshots__/CheckBoxGroup.test.tsx.snap, modules/cactus-web/src/DateInputField/__snapshots__/DateInputField.test.tsx.snap, modules/cactus-web/src/FileInputField/__snapshots__/FileInputField.test.tsx.snap, modules/cactus-web/src/RadioGroup/RadioGroup.tsx, modules/cactus-web/src/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap, modules/cactus-web/src/SelectField/__snapshots__/SelectField.test.tsx.snap, modules/cactus-web/src/TextAreaField/__snapshots__/TextAreaField.test.tsx.snap, modules/cactus-web/src/TextInputField/__snapshots__/TextInputField.test.tsx.snap
Ticket: https://repayonline.atlassian.net/browse/CACTUS-357
I'm targeting `cactus-web-v4` because the `ariaDescribedBy` field returned by `useAccessibleField` can now return `undefined` if no `aria-describedby` attribute should be in the DOM.
1. Open up a story for one of the accessible fields
2. Add/remove the tooltip and status messages.  Inspect the DOM element for the field to ensure that `aria-describedby` only specifies existing elements (i.e. it doesn't reference the tooltip if there is no tooltip).
3. Use a screen reader to make sure that it still picks up the status message/tooltip when focused on the accessible field.
=> CACTUS-357 :: Fix non existent describedby

examples/mock-ebpp/run-ete-tests.js, examples/standard/run-ete-tests.js
It looks like this is working again.  I'm not sure what happened last week.  If you want, you can make sure you can still run the integration tests locally, but that's up to you.
=> Go back to running BrowserStack tests in parallel

modules/cactus-web/src/AccessibleField/AccessibleField.tsx, modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/SelectField/SelectField.tsx
I don't know if this is the best way to solvew the issue, but it does the job (I think).
TO test:
Go to the select field on storybook and check if the problme has been fixed.
[CACTUS-388]
[CACTUS-388]: https://repayonline.atlassian.net/browse/CACTUS-388
=> fix(cactus-web): fix tooltip z index problem with select

modules/cactus-web/src/MenuBar/MenuBar.test.tsx, modules/cactus-web/src/MenuBar/MenuBar.tsx, modules/cactus-web/src/MenuBar/__snapshots__/MenuBar.test.tsx.snap, modules/cactus-web/src/MenuBar/scroll.ts, modules/cactus-web/src/helpers/usePopup.ts
https://repayonline.atlassian.net/browse/CACTUS-387
Works basically the same as before with two minor differences:
- Now when you click a button to expand a menu, you can then use the keyboard (up/down arrows) to start navigating the newly-opened menu.
- If you're using the keyboard to navigate the menu and then you click on a scroll button, you can go back to using the keyboard and it'll pick up where you left off. (Debatably useful, this was just a side effect of `useFocusControl`, not done on purpose.)
=> CACTUS-387 MenuBar + usePopup = Winning

modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/helpers/usePopup.ts
https://repayonline.atlassian.net/browse/CACTUS-405
Should be a quick & easy one. I tested other usages of `relatedTarget` that I found, but I didn't notice any problems. If you happen to notice anything I missed, let me know!
Test the following in both IE and your preferred browser
1. Open the Select "with comboBox" story and focus the combobox input. Click outside the select and make sure the list closes.
2. Open the Layout story and click the gear icon in the action bar. Click outside the panel to make sure it closes when focus leaves the panel.
=> CACTUS-405 :: IE relatedTarget Support

modules/cactus-web/src/MenuBar/MenuBar.tsx, modules/cactus-web/src/MenuBar/__snapshots__/MenuBar.test.tsx.snap, modules/cactus-web/src/MenuBar/scroll.ts
https://repayonline.atlassian.net/browse/CACTUS-412
I looked into using IconButton like the ticket said, but it didn't work out:
- The icons are 18px, which is not an available `IconSize`. Looking at the code I think you could actually pass `iconSize="18px"` and it would work, but you'd have to do `@ts-ignore` _and_ you'd still get a PropTypes warning.
- (I had more reasons, but when I considered them more deeply while writing them out here, I realized they weren't as good as I thought they were.)
=> CACTUS-412 MenuBar scroll buttons are both visible or both hidden

modules/cactus-web/src/Accordion/Accordion.tsx
Test:
Play with the accordion in storybook and check that, regardless of the size, the transition time is the same
[CACTUS-417]
[CACTUS-417]: https://repayonline.atlassian.net/browse/CACTUS-417
=> CACTUS-417: set accordion transition time to 200ms

.gitignore, modules/cactus-fwk/package.json, modules/cactus-i18n/package.json, modules/cactus-icons/package.json, modules/cactus-theme/package.json, modules/cactus-web/package.json, package.json, yarn.lock
Ticket: https://repayonline.atlassian.net/browse/CACTUS-291
The first step is to add a few tools to `cactus` and `ui-tools` so that SonarQube can correctly interpret coverage reports.  There's not much to test here, but you could run `yarn test:sonar` and verify that the `test-report.xml` files are generated, if you want.  Or, you could check out the `cactus` project in SonarQube and make sure that coverage is correctly captured.  See https://sonarqube.repay.ninja/dashboard?id=cactus (you need to be on the VPN)
=> CACTUS-291 :: Add coverage support for SonarQube

modules/cactus-web/src/Select/Select.story.tsx, modules/cactus-web/src/Select/Select.test.tsx, modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/Select/__snapshots__/Select.test.tsx.snap, modules/cactus-web/src/SelectField/__snapshots__/SelectField.test.tsx.snap
In the Select story, basic usage there is a knob to disable the option. If it's false the text "No options available" should be displayed.
In WithCombobox there is the same knob, but for it to show the no options available text, the **canCreateOption** knob should also be disabled.
[CACTUS-429]
[CACTUS-429]: https://repayonline.atlassian.net/browse/CACTUS-429
=> CACTUS-429: allow configurable text for empty optins in select

examples/mock-ebpp/package.json, examples/mock-ebpp/tests/account-integration.test.ts, examples/mock-ebpp/tests/faq-integration.test.ts, examples/mock-ebpp/tests/helpers/actions.ts, examples/mock-ebpp/tests/rules-integration.test.ts, examples/mock-ebpp/tests/ui-config-integration.test.ts, examples/standard/package.json
https://repayonline.atlassian.net/browse/CACTUS-268
Mostly it was the click bug, though it seems Firefox also has a difference in how it formats the file input data, so I had to correct for that.
As far as I could tell, Safari was already passing (at least in browserstack), so I'm not sure what the issue was there.
=> CACTUS-268: workaround testcafe click bug in Firefox

modules/cactus-web/src/Tooltip/Tooltip.test.tsx, modules/cactus-web/src/Tooltip/Tooltip.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-430
Unfortunately, I wasn't able to come up with a solution to close the tooltip without changing the focus when `autoTooltip` is enabled. I did do some investigating, and I think it's possible, but I believe the scope for the changes required would go beyond what I'd feel comfortable adding during work for this ticket. If we want to add that feature, I think we should create a separate ticket for it.
1. Pull down this branch and bring up storybook in your web browser
2. Go to the tooltip story and click the icon
3. Verify that the content window stays open until you click outside the icon or the widget
I tested this using my phone and it worked for me, but if you're able to test it on your mobile device (or an emulator) that'd be …
=> CACTUS-430 :: Updated Tooltip Triggers

modules/cactus-web/src/BrandBar/BrandBar.tsx, modules/cactus-web/src/BrandBar/__snapshots__/BrandBar.test.tsx.snap
Check the logo is no longer stretching on safari, and that it looks ok in all other browsers too
[CACTUS-437]
[CACTUS-437]: https://repayonline.atlassian.net/browse/CACTUS-437
=> CACTUS-437: fix stretching logo in BrandBar in safari

modules/cactus-web/src/BrandBar/BrandBar.tsx, modules/cactus-web/src/BrandBar/__snapshots__/BrandBar.test.tsx.snap
The problem with safari was that it was adding a default margin so I had to delete it.
In edge the button had a border-radius, so I had to delete it too.
Test:
Check the Bottom border in the user menu of the Brandbar looks good in every browser
[CACTUS-441]
[CACTUS-441]: https://repayonline.atlassian.net/browse/CACTUS-441
=> CACTUS-441: fix bottom border in brandbar's user menu in safari and edge

docs/Internationalization/API Documentation.md, docs/Internationalization/Getting Started.md, examples/standard/src/i18nController.ts, modules/cactus-i18n/package.json, modules/cactus-i18n/src/BaseI18nController.ts, modules/cactus-i18n/src/Components.tsx, modules/cactus-i18n/src/hooks.ts, modules/cactus-i18n/src/types.ts, modules/cactus-i18n/tests/__snapshots__/exports.test.ts.snap, modules/cactus-i18n/tests/i18n.test.tsx
https://repayonline.atlassian.net/browse/CACTUS-431
Quite a few breaking changes, but hopefully they should all be centered around the implementation of the controller class, rather than spread all over the place. ~I'm setting this up as a draft PR because I'd like some feedback, but I also want to double-check my work on the actual channels code base. (And I still need to update the docs/example apps.)~
Specifically, the issue I want feedback on is this: the way channels currently does their fallback is to have each section with it's own bundle; when they do a lookup, if they don't find the key in the first bundle they go on to the next, until they run out of bundles to check. The way I implemented it, each section bundle includes all keys from its dependencies, so it only needs to check …
=> CACTUS-431 add support for fallback & hierarchies in i18n

modules/cactus-web/src/Tooltip/Tooltip.tsx, modules/cactus-web/src/Tooltip/__snapshots__/Tooltip.test.tsx.snap
Check the text in the tooltip doesn't overflow on ie11
[CACTUS-442]
[CACTUS-442]: https://repayonline.atlassian.net/browse/CACTUS-442
=> CACTUS-442: fix ie11 word wrap in tooltip

modules/cactus-web/src/Accordion/Accordion.test.tsx, modules/cactus-web/src/Accordion/Accordion.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-466
When accordions were unregistered from an un AccordionProvider, the provider would still have the deleted accordion's ID in the `uncontrolledOpen` state.  This could cause bugs in other parts of the code.
=> CACTUS-466 :: Accordion Deletion Bug

modules/cactus-web/src/Tabs/Tabs.mdx
The space-evenly option triggers a window.navigator check.  This prevents Gatsby from building due
to SSR restrictions.
=> Update justifyContent in Tabs docs

modules/cactus-theme/src/converters.ts, modules/cactus-theme/tests/converters.test.ts, modules/cactus-theme/tests/theme.test.ts
https://repayonline.atlassian.net/browse/CACTUS-468
I think that all hex values go through that one function, so that should be the only change needed. I'm not sure if there's a place this can be manually tested, but I added some spaces randomly in a couple of the unit tests.
=> CACTUS-468: trim spaces from hex color values

modules/cactus-web/src/DataGrid/PageSizeSelect.tsx, modules/cactus-web/src/MenuBar/MenuBar.tsx, modules/cactus-web/src/Pagination/Pagination.mdx, modules/cactus-web/src/Pagination/Pagination.tsx, modules/cactus-web/src/PrevNext/PrevNext.tsx, modules/cactus-web/src/Tabs/Tabs.tsx, modules/cactus-web/src/helpers/a11y.ts
UAT note: https://repayonline.atlassian.net/browse/CACTUS-464
I don't really remember why I went with keypress in the first place, but after some testing I found that keydown worked just as well in all browsers (I tested on button, div, and anchor with and w/out href), as long as it's paired with `onKeyUp={preventAction}` to prevent duplicate click events. As such, I decided to change all the keypress events, even the ones that weren't susceptible to the IE bug, just to make it less confusing for future devs.
=> CACTUS-464: change keypress to keydown to avoid IE bug

modules/cactus-web/src/ActionBar/ActionBar.mdx, modules/cactus-web/src/ActionBar/ActionBar.story.tsx, modules/cactus-web/src/ActionBar/ActionBar.test.tsx, modules/cactus-web/src/ActionBar/ActionBar.tsx, modules/cactus-web/src/BrandBar/BrandBar.tsx, modules/cactus-web/src/Layout/Layout.story.tsx
https://repayonline.atlassian.net/browse/CACTUS-472
BREAKING CHANGE: aria-label prop is now required on ActionBar.Panel & ActionBar.Item
I looked at the other components where a similar change might make sense (Sidebar.Button, BrandBar.Item); for the former, I decided that if devs are springing for the lower-level components they might need greater flexibility; and for the latter, I didn't want to require a prop for an optional situation that only happens on tiny screens, if at all.
=> CACTUS-472: ActionBar ARIA labels

modules/cactus-web/src/Select/Select.test.tsx, modules/cactus-web/src/Select/Select.tsx
https://repayonline.atlassian.net/browse/CACTUS-480
Two parts to this:
1. Making sure values can only be added programmatically if `canCreateOption` is true.
2. Do not display duplicates from the extra options (does not prevent duplicates among passed-in options).
No stories can test this as-is, but if you want to be thorough you can the modifications in the reproduction section of the ticket to test this manually; beyond that I also added a unit test to cover it.
Mike suggested this was a breaking change; is that still the case if the previous behavior was more of a bug than a feature?
=> CACTUS-480: prevent duplicate options in Select

examples/mock-ebpp/src/containers/date.tsx, examples/mock-ebpp/src/containers/ui-config.tsx, examples/mock-ebpp/src/index.tsx, examples/mock-ebpp/tests/date-input-integration.test.ts, examples/mock-ebpp/tests/ui-config-integration.test.ts, modules/cactus-web/src/DateInput/DateInput.tsx
https://repayonline.atlassian.net/browse/CACTUS-476
Since I couldn't think of a way of working the datetime/time inputs into the example app, I made a "hidden" page specifically for the integration tests. With that done, I felt it made more sense to move the existing DateInput tests to that file as well.
Finally, I also fixed an issue where IE (I think it's actually a polyfill library) was adding an extra character to the month names.
=> CACTUS-476: add integration tests for DateInput

modules/cactus-i18n/src/BaseI18nController.ts, modules/cactus-i18n/src/Components.tsx
https://repayonline.atlassian.net/browse/CACTUS-493
This works by delaying the context change until the new language is loaded. Apparently Mari doesn't think this will work for channels, but since the only alternatives I can think of are the previous remounting behavior (which could cause lost state), and flashing the content key names (default behavior for missing translations) while the sections load; I think they'll just have to work around it on their end if they don't like any of those options.
I don't know any way of testing this other than sticking `console.log` statements in the code. Specifically for the remounting bug, I just added this component as a child of an `I18nSection` in the standard example app:
```
class X extends React.Component {
componentDidMount() {
console.log('X …
```
=> CACTUS-493: Fix I18nSection remount bug

examples/mock-ebpp/tests/date-input-integration.test.ts, modules/cactus-web/src/Select/Select.mdx, modules/cactus-web/src/Select/Select.story.tsx, modules/cactus-web/src/Select/Select.test.tsx, modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/Select/__snapshots__/Select.test.tsx.snap, modules/cactus-web/src/SelectField/SelectField.mdx, modules/cactus-web/src/SelectField/SelectField.story.tsx, modules/cactus-web/src/SelectField/SelectField.tsx, modules/cactus-web/src/SelectField/__snapshots__/SelectField.test.tsx.snap, modules/cactus-web/src/helpers/react.ts
https://repayonline.atlassian.net/browse/CACTUS-497
The updated docs should have everything you need to know about how to use it.
Also changed IDs from using both label & value to just value, which is still supposed to be unique and should be less mutable (e.g. from translations and the like). Not sure if that would could as a breaking change or not, since it could be used in scripts.
=> CACTUS-497: support complex options in Select component

docs/How-tos/End-to-End Testing.md, website/src/components/Layout.tsx, website/src/pages/how-tos.tsx
https://repayonline.atlassian.net/browse/CACTUS-503
I think one or two links in this will suffer from the same problem as https://repayonline.atlassian.net/browse/CACTUS-505. I did play around with a couple things to see if I could fix it, but since there's already a ticket for that I didn't want to spend too long on it.
=> CACTUS-503: added how-to guide for ETE testing

README.md
Because we don't want to manually link stuff later.  I'm open to feedback on better places to put this info.
=> docs: update README to talk about the need for cross-referencing JIRA

modules/cactus-fwk/package.json, modules/cactus-i18n/package.json, modules/cactus-icons/package.json, modules/cactus-theme/package.json, modules/cactus-web/package.json, yarn.lock
Blackduck listed `jest-sonar-reporter` as a high Operational Risk since it is now inactive.  This PR replaces it with `jest-sonar`.
There's not much to test.  Just make sure the tests still run and that `test-report.xml` is still being generated in the various module folders.
=> CACTUS-508 :: Update Jest Sonar Package

modules/cactus-web/src/IconButton/IconButton.tsx
following the suggested solution, warning and success were added to the variant's proptypes
[CACTUS-524](https://repayonline.atlassian.net/browse/CACTUS-524)
=> fix(cactus-web): fix iconbutton warning

modules/cactus-web/src/SelectField/SelectField.story.tsx, modules/cactus-web/src/Tag/Tag.tsx, modules/cactus-web/src/Tag/__snapshots__/Tag.test.tsx.snap
https://repayonline.atlassian.net/browse/CACTUS-525
Technically I just needed to set the default `standard` color style, but who knows what the future holds, and what other use cases may pop up? Since it was just as easy to allow any color style, I figured why not.
=> CACTUS-525: added color styles to Tag component

docs/Components/API Documentation.md, docs/Components/README.md, docs/Framework/API/README.md, docs/Framework/README.md, docs/How-tos/End-to-End Testing.md, docs/How-tos/Forms.md, docs/Icons/README.md, docs/Internationalization/Getting Started.md, docs/Internationalization/README.md, docs/README.md, docs/Theme/README.md, modules/cactus-web/src/DateInput/DateInput.test.tsx
I changed only the links with relative paths. All the URLs stay using the _markdown_ way to write links. 
I discovered that it is not necessary to change the file format from `md` to `mdx` to use Gatsby's `<Link>` API, so I have decided to preserve the original file format. 
[CACTUS-536](https://repayonline.atlassian.net/browse/CACTUS-536)
=> CACTUS 536: Changing Gatsby links format. 

modules/cactus-web/src/Select/Select.story.tsx, modules/cactus-web/src/Select/Select.test.tsx, modules/cactus-web/src/Select/Select.tsx
Ticket and UAT: https://repayonline.atlassian.net/browse/CACTUS-551
The code change was pretty straightforward.  I added a few tests as well to increase our coverage around these edge cases.
As I was tinkering with the tests, I noticed that we were calling `rerender` a lot in that file when we didn't need to, so I decided to quickly pull out all of those calls (a couple were actually useful, so I didn't take out _all_ of them).  I put those changes in a separate commit, so if you want to see my changes without that refactor, just look at the diff from my second commit.
=> CACTUS-551 :: Redundant onChange in Select

modules/cactus-web/src/Layout/Layout.story.tsx, modules/cactus-web/src/MenuBar/MenuBar.tsx, modules/cactus-web/src/MenuBar/__snapshots__/MenuBar.test.tsx.snap
Ticket: https://repayonline.atlassian.net/browse/CACTUS-556
So if you look [here](https://caniuse.com/mdn-css_properties_width_max-content) you'll see that caniuse says that `width: max-content;` is not supported in IE11, but it's working for me now. It wasn't working at first, when I was only applying the style to sub-menus, but when I started setting it on all menus it began to work. I'd say be extra thorough when testing IE11 since it doesn't look like it should be supported.
1. Open the Layout "Basic Usage" story
2. Open the "Interlude: About Bears" menu and then open the "Long Bears" sub-menu.
3. Verify that the width of the sub-menu is 320px wide.
=> CACTUS-556 :: MenuBar Sub-Menu Width

modules/cactus-web/src/Accordion/Accordion.tsx, modules/cactus-web/src/Accordion/__snapshots__/Accordion.test.tsx.snap
added a [flex:1](https://www.w3schools.com/cssref/css3_pr_flex.asp) property to the Accordion header to adjust the length of the flexible items
[CACTUS-564](https://repayonline.atlassian.net/browse/CACTUS-564)
=> fix(cactus-web): accordion IconButton Issue

modules/cactus-web/src/FileInput/FileInput.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-575
1. Pull down this branch and run `yarn web cleanup && yarn web build`
2. In Channels, copy & paste this line into the `docker-compose.yml` file in the admin container under the `volumes` section: `- ../cactus/modules/cactus-web/dist:/code/node_modules/@repay/cactus-web/dist`
3. Run `make init` in the Channels repo
4. When your channels instance is up and running, open FireFox and log in to the app there. Make your way to `https://owe.channels.dev.repay.localhost/admin/#/public-assets/create`
5. Upload a file and make sure the image appears on the page and that the submit button is enabled.
6. Complete step 5 in other browsers of your choosing.
=> CACTUS-575 :: Fix FileInput onChange not Firing

modules/cactus-web/src/Footer/Footer.test.tsx, modules/cactus-web/src/Footer/Footer.tsx, modules/cactus-web/src/Link/Link.tsx
Passed the same props of the Link component allowing `as`
[CACTUS-580](https://repayonline.atlassian.net/browse/CACTUS-580)
Please, let me know if there is something I can do better. 
Thanks!
=> feat(cactus-web) :: Footer link props

modules/cactus-web/src/BrandBar/BrandBar.tsx, modules/cactus-web/src/MenuBar/MenuBar.tsx, modules/cactus-web/src/MenuBar/__snapshots__/MenuBar.test.tsx.snap
Ticket: https://repayonline.atlassian.net/browse/CACTUS-609
Honestly, I still don't really know exactly what was causing this. I think it was something to do with `AceEditor`, because it was only happening on pages that use it, but that's about all I could figure out. John seemed to think it was related to `transform: translateZ(0);` in the `ace_cursor` class, but I didn't see evidence of that. I do know, however, that this fixes it. 🤷‍♂️ 
Also, I had to increase the z-index on the user menu dropdown in `BrandBar`, so that it renders above the `MenuBar`.
1. Check out this branch and run `yarn web cleanup && yarn web build`.
2. Open up the `docker-compose.yml` file in `repay-api` and add this line to the `volumes` section under `admin-ui`:
`- …
=> CACTUS-609 :: Safari MenuBar Fix

modules/cactus-web/src/ColorPicker/ColorPicker.tsx
There was a bit of code in the ColorPicker component that is incompatible with Gatsby's SSR, and therefore prevented the docs from publishing.  Behold...a fix.
=> ColorPicker Docs Fix

modules/cactus-web/package.json, modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/index.ts
Webpack 5 is more agressive with tree shaking than Webpack 4, and it was removing our `polyfills.ts` file from the bundle.  This PR ensures that it is always included.  (The addition of `src/helpers/polyfills.ts` to the `sideEffects` field also ensures that it's included in the `cjs` bundle as well...it wasn't before since this line was missing, causing Rollup to ignore it.)
Ticket: https://repayonline.atlassian.net/browse/CACTUS-634
1. Generate a bare-bones app with `create-repay-ui`
2. `cd` into your new application.  Upgrade `@repay/scripts` to v3.0.0.
3. Run `yarn start`, then try to load the application in IE11.
4. Confirm that it fails to load.  This is the bug.
5. Pull down this branch, and run `yarn cleanup && yarn build`.
6. `cd modules/cactus-web` and `yalc publish`.
7. Go back …
=> CACTUS-634 :: Polyfills Bug

modules/cactus-web/src/MenuBar/MenuBar.tsx
https://repayonline.atlassian.net/browse/CACTUS-646
The problem is that for some reason IE has trouble with a scrollable container inside a flex container. The only way to fix that was to put a max height, but that was causing the flickering when the menu height was between the max and max - buttons. To fix it, I just had to adjust the max to account for whether or not the buttons are visible; in some of my tests that led to a single flicker, but since max-height is the only solution (out of many I tried) that works, and it's IE, I don't think I care.
Also simplified the style a bit.
=> CACTUS-646: fix stutter on transition with/without scroll buttons

modules/cactus-web/src/DataGrid/BottomSection.tsx, modules/cactus-web/src/DataGrid/DataGrid.story.tsx, modules/cactus-web/src/DataGrid/DataGrid.tsx, modules/cactus-web/src/DataGrid/DataGridTable.tsx, modules/cactus-web/src/DataGrid/TopSection.tsx, modules/cactus-web/src/DataGrid/helpers.ts, modules/cactus-web/src/DataGrid/types.ts, modules/cactus-web/src/Table/Table.story.tsx, modules/cactus-web/src/Table/Table.test.tsx, modules/cactus-web/src/Table/Table.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-578
1. Check out this branch and start storybook
2. Bring up the Table > Layout story.
3. Set the variant to `mini`. Uncheck the `fullWidth` checkbox. Make sure the styles match the style guide. Question: should we still adhere to the `fullWidth` prop if the variant is `mini`?
4. Open the DataGrid > Basic Usage story. Set the variant to `mini` and make sure the styles match what's shown in the style guide.
=> CACTUS-578 :: Mini Table

modules/cactus-web/src/Notification/Notification.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-650
So this got me thinking when I picked it up...although the only children I've ever seen rendered in `Notification` are `Alert`s, it doesn't mean that's the _only_ thing you could render in there. I just don't know if we can reliably get child border-radius styles and apply them to the wrapper. I guess it won't matter soon since we'll be updating the colors and we can get rid of the wrapper altogether, so I suppose this will do for now.
1. Pull down this branch and start storybook.
2. Go to the Notification > Basic Usage story.
3. Open the "Cactus Theme" tab in the storybook knobs section and check the "Inverse" checkbox under "Background".
4. Click the button to open the notification and make sure you don't see any white corners …
=> CACTUS-650 :: Notification Border Radius

modules/cactus-web/src/Avatar/Avatar.mdx, modules/cactus-web/src/Breadcrumb/Breadcrumb.mdx, modules/cactus-web/src/CheckBoxGroup/CheckBoxGroup.mdx, modules/cactus-web/src/ConfirmModal/ConfirmModal.mdx, modules/cactus-web/src/DataGrid/DataGrid.mdx, modules/cactus-web/src/Dimmer/Dimmer.mdx, modules/cactus-web/src/Divider/Divider.mdx, modules/cactus-web/src/Flex/Flex.mdx, modules/cactus-web/src/Footer/Footer.mdx, modules/cactus-web/src/Layout/Layout.mdx, modules/cactus-web/src/MenuButton/MenuButton.mdx, modules/cactus-web/src/Modal/Modal.mdx, modules/cactus-web/src/PrevNext/PrevNext.mdx, modules/cactus-web/src/ScreenSizeProvider/ScreenSizeProvider.mdx, modules/cactus-web/src/Spinner/Spinner.mdx, modules/cactus-web/src/SplitButton/SplitButton.mdx, modules/cactus-web/src/StyleProvider/StyleProvider.mdx, website/src/components/Layout.tsx, website/src/components/PropsTable.tsx
https://repayonline.atlassian.net/browse/CACTUS-630
Also fixed a few other problems with bad links, grammar, outdated info, etc., though I'm sure I didn't get everything.
The doc generator seems so random... A few components have their filename from `dist` instead of `src`; some components have an automatically generated `displayName`, some don't, and some don't even seem to work when they have an _explicit_ `displayName`. Grr.
=> CACTUS-630: fix props tables for various components

modules/cactus-web/src/MenuBar/MenuBar.tsx, modules/cactus-web/src/MenuBar/scroll.ts
[CACTUS-658](https://repayonline.atlassian.net/browse/CACTUS-658)
This is my solution to this ticket. I just wanted to implement a dynamic `min-width` value depending on the `MenuButton` `width`,
I followed [this](https://medium.com/vimeo-engineering-blog/handling-internal-and-external-refs-to-the-same-element-with-useimperativehandle-in-react-746ff6d377fe) approach.
I would like to validate with you guys if what I've done is a valid solution and it doesn't _block_ any feature. 
1. Pull this branch and run the stories. 
2. Go to the Layout story and check if the dropdown item in the MenuBar works well and the floating menu is currently taking the same width as their menu button.
=> CACTUS-658 :: Increase MenuBar dropdown min-width

modules/cactus-theme/src/theme.ts, modules/cactus-theme/tests/theme.test.ts
Ticket and UAT: https://repayonline.atlassian.net/browse/CACTUS-651
As discussed, the generated theme in these instances will not be accessible.  But Channels will throw a warning anyway, so it shouldn't be a problem.  This is certainly better than ignoring the color!
=> CACTUS-651 :: Stop ignoring light secondary colors in generateTheme

docs/Design Guides/Theme.mdx, modules/cactus-theme/src/theme.ts, modules/cactus-theme/tests/theme.test.ts, modules/cactus-web/package.json, modules/cactus-web/src/Alert/Alert.tsx, modules/cactus-web/src/DateInput/DateInput.tsx, modules/cactus-web/src/FileInput/FileInput.tsx, modules/cactus-web/src/Footer/Footer.tsx, modules/cactus-web/src/Link/Link.tsx, modules/cactus-web/src/Modal/Modal.tsx, modules/cactus-web/src/StatusMessage/StatusMessage.tsx, modules/cactus-web/src/StyleProvider/StyleProvider.tsx, modules/cactus-web/src/Table/Table.tsx, modules/cactus-web/src/helpers/status.ts, modules/cactus-web/src/helpers/theme.ts
Ticket and UAT: https://repayonline.atlassian.net/browse/CACTUS-661
Note that, with Hector's approval, I ditched the box shadow on the Modal.  You couldn't really see it anyway in the old version, since it was a transparent color over a very dark background.  The new shadow, because it's no longer transparent, just looked weird and bright against the dark background (see attached screenshot).  So we just got rid of it.
Otherwise, there should be no visible changes to any components.
=> CACTUS-661 :: Flatten Action Colors

modules/cactus-web/src/Link/Link.tsx, modules/cactus-web/src/PrevNext/PrevNext.tsx
https://repayonline.atlassian.net/browse/CACTUS-647
Link has an `as` prop, anchor does not. Doesn't exactly fix the underlying problem with conflicting types on the `as` prop; to be honest I hate how ridiculously complicated the `styled-components` types are, and think maybe I could do better myself, but I'll do that on my own time, if at all.
=> CACTUS-647: fix incorrect link types (<link> != <a>)

docs/Theme/README.md, docs/Theme/Style Helpers.md, modules/cactus-theme/package.json, modules/cactus-theme/src/converters.ts, modules/cactus-theme/src/helpers/base.ts, modules/cactus-theme/src/helpers/borders.ts, modules/cactus-theme/src/helpers/breakpoints.ts, modules/cactus-theme/src/helpers/colors.ts, modules/cactus-theme/src/helpers/index.ts, modules/cactus-theme/src/helpers/shadows.ts, modules/cactus-theme/src/helpers/sizes.ts, modules/cactus-theme/src/index.ts, modules/cactus-theme/src/theme.ts, modules/cactus-theme/tests/__snapshots__/exports.test.ts.snap, modules/cactus-theme/tests/border-helpers.test.ts, modules/cactus-theme/tests/breakpoint-helpers.test.ts, modules/cactus-theme/tests/color-helpers.test.ts, modules/cactus-theme/tests/exports.test.ts, modules/cactus-theme/tests/helpers.ts, modules/cactus-theme/tests/shadow-helpers.test.ts, modules/cactus-theme/tests/size-helpers.test.ts, modules/cactus-theme/tests/theme.test.ts, modules/cactus-theme/tsconfig.build.json, modules/cactus-theme/tsconfig.json
https://repayonline.atlassian.net/browse/CACTUS-664
I added all the helpers from channels + cactus-web, although the API is more like what I did in channels. I even added a couple of new ones, so we pretty much cover every theme attribute.
If anyone can think of a better name for the media query helpers than `mediaGTE` and `mediaLT`, that'd be great: I really don't like those names, but couldn't think of anything better that wasn't several words long.
Last thing to be aware of is that I changed some things about the build/Typescript config. It worked within the repo, but I don't know much about JS packaging, so hopefully it'll still work after it's deployed. Make sure you do `yarn cleanup` before testing, though, to get rid of the old build code.
Finally, if you want to see the new …
=> CACTUS-664 Theme Style Helpers

actions/integration-tests/Dockerfile
The Docker image in the CI pipeline seems to be pulling a weird version of node that's causing issues.  This ensures that we use some flavor of node v14.
=> Fix a Docker error in the integration tests

modules/cactus-web/src/AccessibleField/AccessibleField.tsx, modules/cactus-web/src/DateInputField/DateInputField.tsx, modules/cactus-web/src/FileInputField/FileInputField.story.tsx, modules/cactus-web/src/FileInputField/FileInputField.tsx, modules/cactus-web/src/SelectField/SelectField.story.tsx, modules/cactus-web/src/SelectField/SelectField.tsx, modules/cactus-web/src/TextAreaField/TextAreaField.tsx, modules/cactus-web/src/TextInputField/TextInputField.tsx, modules/cactus-web/src/Tooltip/Tooltip.story.tsx, modules/cactus-web/src/Tooltip/Tooltip.tsx
UAT: https://repayonline.atlassian.net/browse/CACTUS-677
I basically just added `tooltipProps` wherever I saw `labelProps`. Note that I also fixed some of the prop types, which were incorrect for `error`, `warning`, `success`, and `tooltip`, and removed some pointless defaults.
=> CACTUS-677 Tooltip Color

modules/cactus-web/src/CheckBox/CheckBox.story.tsx, modules/cactus-web/src/CheckBox/CheckBox.test.tsx, modules/cactus-web/src/CheckBox/CheckBox.tsx, modules/cactus-web/src/CheckBoxField/CheckBoxField.test.tsx, modules/cactus-web/src/CheckBoxField/CheckBoxField.tsx, modules/cactus-web/src/RadioButton/RadioButton.story.tsx, modules/cactus-web/src/RadioButton/RadioButton.test.tsx, modules/cactus-web/src/RadioButton/RadioButton.tsx, modules/cactus-web/src/RadioButtonField/RadioButtonField.test.tsx, modules/cactus-web/src/RadioButtonField/RadioButtonField.tsx, modules/cactus-web/src/TextArea/TextArea.story.tsx, modules/cactus-web/src/TextArea/TextArea.test.tsx, modules/cactus-web/src/TextArea/TextArea.tsx, modules/cactus-web/src/TextAreaField/TextAreaField.test.tsx, modules/cactus-web/src/TextAreaField/TextAreaField.tsx, modules/cactus-web/src/TextInput/TextInput.story.tsx, modules/cactus-web/src/TextInput/TextInput.test.tsx, modules/cactus-web/src/TextInput/TextInput.tsx, modules/cactus-web/src/TextInputField/TextInputField.test.tsx, modules/cactus-web/src/TextInputField/TextInputField.tsx, modules/cactus-web/src/Toggle/Toggle.test.tsx, modules/cactus-web/src/Toggle/Toggle.tsx, modules/cactus-web/src/ToggleField/ToggleField.test.tsx
https://repayonline.atlassian.net/browse/CACTUS-782
Individual commit messages have a bit more info, but the short story is that I did four main things:
- Added ref support where it didn't already exist.
- Added tests to prove that the refs are assigned to the correct element and that Typescript has the correct type.
- Refactored the styles with the theme helpers.
- On TextInput and TextArea, I changed how the width/height props are applied so that the resulting element is actually the correct dimension, not just visually so.
- On CheckBox and RadioButton I also moved the disabled styles so we wouldn't have to pass that prop to the visible psuedo input.
- Made `id` optional on CheckBox and RadioButton, and `name` optional on Checkbox, since there's no reason for it to be required. (Not …
=> CACTUS-782 Input refs

modules/cactus-web/src/ColorPicker/ColorPicker.story.tsx, modules/cactus-web/src/ColorPicker/ColorPicker.tsx, modules/cactus-web/src/DateInput/DateInput.tsx, modules/cactus-web/src/FileInput/FileInput.story.tsx, modules/cactus-web/src/FileInput/FileInput.tsx, modules/cactus-web/src/FileInputField/FileInputField.tsx, modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/TextArea/TextArea.tsx, modules/cactus-web/src/TextInput/TextInput.tsx, modules/cactus-web/src/helpers/status.ts
https://repayonline.atlassian.net/browse/CACTUS-726
As is becoming a habit, individual commit messages may have a few extra details.
Incidentally, although I'm relatively sure that DateInput and FileInput don't need `id`/`name` to be required any more than ColorPicker, they're significantly more complex and I didn't want to make that change and then be proven wrong (nor did I want to comb through the code to verify a change that has nothing to do with this ticket).
=> CACTUS-726 Input Status Styles

docs/Forms/README.md, docs/How-tos/Forms.md
https://repayonline.atlassian.net/browse/CACTUS-806
Since Cactus Form is specifically designed with the Cactus Web fields in mind, the fields section is a bit shorter now.
=> CACTUS-806: change how-to-docs from formik to final-form

examples/mock-ebpp/package.json, modules/cactus-form/package.json, modules/cactus-fwk/package.json, modules/cactus-icons/package.json
So it turns out, when publishing a scoped package for the first time, you have to pass the `--access public` flag. Lerna doesn't do this, so when I ran the script, it published `cactus-icons` and `cactus-fwk` successfully, then got to `cactus-form` and failed.
Now that I manually published `cactus-form` with the flag, we just need to bump the versions of the packages that were already published so that lerna doesn't try to publish them again when I run the script again.
=> Fix Publish

docs/Theme/README.md, modules/cactus-theme/src/theme.ts, modules/cactus-theme/tests/theme.test.ts, modules/cactus-web/cactus-addon/register.jsx
[CACTUS-821](https://repayonline.atlassian.net/browse/CACTUS-821)
This is my current approach on this:
I created the `saturationMultiplier` variable and added to the theme object. Set 1 as default and multiplied that factor with every saturation value of the `hsl` representations of the following colors: 
- Base
- CTA
- CTA light
- Contrast light
- Contrast Medium
- Contrast Dark
- Contrast Darkest
I added one range control for that Saturation Multiplier into the `Cactus Theme` addon in the Storybook app of the `cactus-web` module. So you can run the storybook app and test that. 
Don't forget to add the current version of the `theme` package using `yalc`.
=> CACTUS-821 :: Saturation Multiplier 

modules/cactus-web/src/IconButton/IconButton.tsx, modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/Tag/Tag.mdx, modules/cactus-web/src/Tag/Tag.story.tsx, modules/cactus-web/src/Tag/Tag.test.tsx, modules/cactus-web/src/Tag/Tag.tsx
https://repayonline.atlassian.net/browse/CACTUS-738
I kind of recycled the `closeOption` prop for setting it to not be a button, since the name seemed to fit, and I could add an option to it while still being backwards compatible. Other changes:
- Fixed some prop types, including removing a completely redundant one from `IconButton`.
- Removed the `data-role="close"` prop, which seems to have been basically a hack to make implementing the `Select` component easier.
- In its place, added the `aria-controls` prop; fulfills basically the same purpose in terms of CSS queries, but also gives an easier reference to the tag, making it easier to share a single handler for multiple tags.
IE sucks as usual.
=> CACTUS-738: change Tag close icon to button

modules/cactus-web/src/Calendar/Grid.tsx, modules/cactus-web/src/DateInput/DateInput.test.tsx, modules/cactus-web/src/DateInput/DateInput.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-755
1. Open the `DateInput` "Basic Usage" story and open up the calendar. Make sure it initially focuses on the current day.
2. Now use the `initialFocus` control to set a date to initially focus on. Open the calendar and make sure the correct date is focused.
3. Set a value in the `DateInput`, then open the calendar again (keeping the `initalFocus` value) and make sure the value you set is initially focused instead of the date in the `initialFocus` prop.
=> CACTUS-755 :: DateInput initialFocus

modules/cactus-web/src/DateInput/DateInput.test.tsx, modules/cactus-web/tests/helpers/renderWithTheme.tsx
Had some extra time and I've been thinking about doing this for a while so I figured I'd put up a rough draft and see what you guys think.
Basically I want to replace all of the `render` usage in our tests with this `renderWithTheme` function I wrote. I just started with `DateInput` tests since that's the test file I had open. It's pretty simple, but it removes a lot of repetitive lines that aren't specific to any tests. I figure if we do this, we could also just do some general cleanup where it makes sense, too. For instance, here I got rid of all of the unnecessary return value types and imported `animationRender` instead of re-defining it in this file.
So do you guys think this is worth our time? Do you think there are any use cases I may have missed? We're light on work right now so I …
=> Test Cleanup

modules/cactus-web/src/Alert/Alert.tsx, modules/cactus-web/src/Button/Button.tsx, modules/cactus-web/src/Flex/Flex.tsx, modules/cactus-web/src/Spinner/Spinner.tsx, modules/cactus-web/src/Table/Table.tsx, modules/cactus-web/src/TextArea/TextArea.tsx
https://repayonline.atlassian.net/browse/CACTUS-753
`Flex`, `Spinner`, and `TextArea` were the only ones I found that currently had this issue. There were quite a few places, though, where we _could_ be using `styled-system` to implement responsive styles, but are not; I'll probably go through them one of these days and make some tickets.
`justifyContent` is a special case, unfortunately, as long as we have to support IE. I did try to make a responsive version of the fix, but unlike regular styles, the `::before` and `::after` pseudo-elements don't just disappear as they're overridden.
I added a couple of other minor Typescript fixes and removed some propTypes for the `as` prop, which I think were probably incorrect and almost certainly pointless.
=> CACTUS-753: fix styled-system `propTypes`

modules/cactus-web/src/Select/Select.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-898
I updated the prop type for noOptionsText as well as `placeholder` (They get used in the same place so they should be the same type), and as per a conversation with glen, `matchNotFoundText` because it should be a node too for the same reason as `noOptionsText`.
=> cactus-898:: set prop type nooptionstext select

.github/workflows/snyk-scan.yml, actions/snyk/action.yml
https://repayonline.atlassian.net/browse/CACTUS-899
I tested the action and it works, but we won't know if the "on merge" condition works till we merge this PR. For now I just set the `SNYK_TOKEN` to my personal token, we can switch that out at any time.
Here's the successful run: https://github.com/repaygithub/cactus/actions/runs/2430326793
=> CACTUS-899: use snyk cli to monitor repo

modules/cactus-web/src/BrandBar/BrandBar.tsx
[CACTUS-929](https://repayonline.atlassian.net/browse/CACTUS-929)
Renders LogoWrapper if `logo` is not undefined. The change is applied not only for tiny screens, I consider the `isTiny` check unnecessary so the blank space is removed from both tiny and larger screens.
=> CACTUS-929 :: Fix BrandBar when no `logo`

.github/workflows/master-workflow.yml
[CACTUS-966](https://repayonline.atlassian.net/browse/CACTUS-966)
Hey, want to add a new workflow to cactus but it seems I don’t have permission for doing that:
I created the branch and the file directly here on Github... but maybe there are some permissions we need to be assigned to my profile for future workflow-related tickets.
=> ci(cactus-web) :: Have merges to master automatically run docs:publish on merge on Cactus

.github/workflows/master-workflow.yml
[CACTUS-966](https://repayonline.atlassian.net/browse/CACTUS-966) 
Added the `yarn install` step to this workflow:
not sure if a `yarn build` step should be necessary for this. If this fails, I'll open this again and then add that step.
=> CACTUS-966 :: Have merges to master automatically run docs:publish on merge on Cactus

modules/cactus-web/src/Box/Box.story.tsx, modules/cactus-web/src/Box/Box.tsx, modules/cactus-web/src/Text/Text.story.tsx, modules/cactus-web/src/Text/Text.tsx, modules/cactus-web/src/helpers/storybook.ts, modules/cactus-web/src/helpers/styled.ts
UAT: https://repayonline.atlassian.net/browse/CACTUS-963
There turned out to be quite a few properties here:
- `textDecoration`: brings underline & strikethrough, which are both useful
- `textOrientation`/`writingMode`: I thought these might be useful someday in vertical table labels or something, to save space
- `textTransform`: we've already used this in a couple of header-ish components
- `fontVariant`: seems like a more useful & flexible version of `textTransform`
- `textOverflow`: we've mostly handled this internally in components, but I wouldn't be surprised if it came up somewhere outside of those
- some of those are shortcut properties, so I included the full versions as well
`color` is foreground (usually text) color, so I included it in AllTextProps. Overflow doesn't quite fit, …
=> CACTUS-963: add variety of text-related styling props

package.json, website/gatsby-config.js, website/gatsby-node.js, website/package.json, website/src/components/Layout.tsx, website/src/components/PropsTable.tsx, yarn.lock
I left the stuff I'm removing here in another branch called `broken-docs-versioning`, and I pinned `devcert` since that was causing issues with running the docs site locally.
#732 was the original if you want to compare these changes with the PR where they were added.
=> Remove Docs Versioning

package.json, yarn.lock
Ticket: [CACTUS-979](https://repayonline.atlassian.net/browse/CACTUS-979)
UAT:
Not really sure how to write it for this...Basically everything here was a patch except for the ansi-regex library which moved from 2.1.1 to 3.0.0 so make sure that it didn't break anything.
=> cactus-979:: fix docs website snyk vulnerability

actions/integration-tests/Dockerfile, actions/storyshots/Dockerfile
https://repayonline.atlassian.net/browse/CACTUS-981
This image was missing a few things that we needed (`wget`, `unzip`, `procps`), but seems to be working now that I added them.
https://repayonline.atlassian.net/browse/CACTUS-982
I wasn't able to install `libappindicator1` with this image, but apparently we don't need it. Also had to add `procps` to this one too.
Nothing to test for either of these. If we get some green checkmarks we should be good to go.
=> CACTUS-981/982 :: Fix Snyk Issues

docs/Components/Hooks.md, modules/cactus-web/src/DataGrid/DataGrid.mdx, modules/cactus-web/src/DataGrid/DataGrid.story.tsx, modules/cactus-web/src/DataGrid/DataGrid.test.tsx, modules/cactus-web/src/DataGrid/DataGrid.tsx, modules/cactus-web/src/DataGrid/DataGridTable.tsx, modules/cactus-web/src/DataGrid/PageSizeSelect.tsx, modules/cactus-web/src/DataGrid/Pagination.tsx, modules/cactus-web/src/DataGrid/TopSection.tsx, modules/cactus-web/src/DataGrid/helpers.ts, modules/cactus-web/src/DataGrid/types.ts, modules/cactus-web/src/hooks.ts, modules/cactus-web/src/hooks/tests/useControllableValue.test.tsx, modules/cactus-web/src/hooks/tests/useRefState.test.tsx, modules/cactus-web/src/hooks/useControllableValue.ts, modules/cactus-web/src/hooks/useRefState.ts, modules/cactus-web/src/index.ts, modules/cactus-web/tests/__snapshots__/exports.test.ts.snap
https://repayonline.atlassian.net/browse/CACTUS-969
This consists of three changes:
- Added `itemCount` and `itemOffset` as alternatives to `pageCount` and `currentPage` respectively (`pageSize` required to use).
- Added ability to control pagination via props passed directly to `PageSizeSelect`, `Pagination`, and `PrevNext`.
- Along with this, I moved most of the pagination-related logic to its own file.
- Added `onPagisort` handler, combining `onSort` & `onPageChange` and allowing pagination & sorting to be done uncontrolled.
Originally this would have involved making `currentPage` and `pageCount` optional properties, but it turns out that would have been a breaking change to the `onPageChange` handler.
Also made some story changes:
- Sort is now entirely uncontrolled.
- Pagination is …
=> CACTUS-969: add more ways of pagination to DataGrid

modules/cactus-web/src/DataGrid/DataGrid.story.tsx, modules/cactus-web/src/DataGrid/DataGridTable.tsx
https://repayonline.atlassian.net/browse/CACTUS-1022
Even easier than I expected. Basically, the `text-align` property only applies to inline elements, so we just make the button inline.
=> CACTUS-1022: apply cell alignment to sortable columns

modules/cactus-web/src/Table/Table.tsx, modules/cactus-web/src/helpers/positionPopover.ts
https://repayonline.atlassian.net/browse/CACTUS-1016
You can UAT this on the `DataGrid` story.
This is kind of a hacky solution; if we switch to using portals, this whole commit can just be reverted.
- The MutationObserver fixes the issue of popups appearing underneath the next row(s).
- The scroll parent change fixes the issue of popups being hidden by the table's scroll container. (Not mentioned in the ticket, but can easily be seen by opening the drop-down on the last row; somehow doesn't appear to happen on Chrome, though? It does on Firefox.)
=> CACTUS-1016: fix popup overlap with sticky positioning

examples/mock-ebpp/src/containers/ui-config.tsx, modules/cactus-web/src/Flex/Flex.mdx, modules/cactus-web/src/Flex/Flex.story.tsx, modules/cactus-web/src/Flex/Flex.test.tsx, modules/cactus-web/src/Flex/Flex.tsx, modules/cactus-web/src/Footer/Footer.tsx, modules/cactus-web/src/Modal/Modal.tsx, modules/cactus-web/src/helpers/styled.ts
UAT: https://repayonline.atlassian.net/browse/CACTUS-998
I also moved the `space-evenly` fix into the styled-system code, and removed some properties that have no effect on flex layouts (`justifyItems` & `justifySelf`).
The `Flex.Item` component is just because I've come across quite a few situations where I wanted to set a flex property, but the component I was using didn't support them.
Because `Modal` and `Footer` also utilize the `flexContainer` styles, I added the gap workaround to them as well.
=> CACTUS-998: support Flex gap property; add `Flex.Item`

actions/integration-tests/Dockerfile, actions/storyshots/Dockerfile, examples/mock-ebpp/package.json, examples/standard/package.json, yarn.lock
https://repayonline.atlassian.net/browse/CACTUS-1009
UAT is just doing anything you can think of. Focus on stuff that's not covered by the automated stuff, of course, but it won't hurt if there's overlap.
I upgraded everything possible among transient dependencies, but I suspect we'll still have the same vulnerabilities as before since they're through storybook, which we can't upgrade right now, and gatsby/lerna which are already at the latest versions.
=> CACTUS-1009 Snyk fixes

modules/cactus-web/src/TextArea/TextArea.tsx, modules/cactus-web/src/TextInput/TextInput.tsx, modules/cactus-web/src/helpers/status.ts
https://repayonline.atlassian.net/browse/CACTUS-1043
I just refactored so all the common styles, including the italic, are in one place. I was going to add the min-width override that I talked about, but with the extra div there I don't think it's possible. With `width` you can just change from "auto" to "100%", but if you set `min-width: 100%`, that's going to change the actual width, not the min-width; and if you set it to the same value as the outer div, `min-width: 50%` would effectively be 25% instead. We'll just have to defer that change to https://repayonline.atlassian.net/browse/CACTUS-1055.
=> CACTUS-1043: add italic placeholder styles to TextArea

modules/cactus-web/src/Dimmer/Dimmer.tsx, modules/cactus-web/src/IconButton/IconButton.tsx, modules/cactus-web/src/Modal/Modal.tsx, modules/cactus-web/src/helpers/portal.ts
https://repayonline.atlassian.net/browse/CACTUS-765
The biggest things Reach did were scroll trapping (although they did it in a really weird way that broke our layout), focus lock, and handling visibility/events. We already had scroll trapping code, a focus lock, and the Dimmer that controls visibility; that just left the events, which are quite simple. The only really new thing here is the portal.
Also, there's one thing they did which I didn't, because it seemed like overkill: they set `aria-hidden` on everything _but_ the open modal.
=> CACTUS-765 Reach-less Modal

modules/cactus-web/src/Layout/grid.ts
Ticket and UAT: https://repayonline.atlassian.net/browse/CACTUS-1063
I have tested this in _so many_ (probably more than necessary) different device/browser combinations that I'm feeling pretty confident at this point.
I tested channels admin, merchant, and customer apps with:
- Desktop Chrome
- Desktop Firefox
- Desktop Safari
I tested channels merchant and customer apps with:
- IE11
- Newest iOS/Chrome
- Various older iOS/Chrome combos
- Newest iOS/Safari
- Varying older iOS/Safari combos (including Safari 14)
- Newest Android/Chrome (Samsung, Google, and OnePlus devices)
- Various older Android/Chrome combos
- Newest Android/Firefox
- _Some_ older Android/Firefox combos (some older versions of firefox didn't allow me to access localhost)
- I even tested on some obscure Android browsers …
=> CACTUS-1063 :: Fix Layout Height Bug

modules/cactus-web/src/Dimmer/Dimmer.tsx
[CACTUS-1060](https://repayonline.atlassian.net/browse/CACTUS-1060)
I guess the title of this should be different. 
I spent more time struggling with how to build a local version of the `react-ui-base-image` to test this in channels. But I got it and it worked. 
Feel free to test by yourself. I did it with iOS and android.
=> CACTUS-1060 :: Remove `vh` styles from Dimmer

modules/cactus-web/src/ScreenSizeProvider/ScreenSizeProvider.test.tsx, modules/cactus-web/src/ScreenSizeProvider/ScreenSizeProvider.tsx
[CACTUS-970](https://repayonline.atlassian.net/browse/CACTUS-970)
I tested this using `mock-ebpp`, just added a local version of `cactus-web` (previously built) using yalc, ran `yarn && yarn install`, and ensure the app isn't broken in our loved IE11
=> CACTUS-970 :: ScreenSizeProvider using deprecated function

modules/cactus-web/src/Dimmer/Dimmer.mdx
Follow up fix for [CACTUS-1008](https://repayonline.atlassian.net/browse/CACTUS-1008). It's strange, I know when I make changes to the docs I usually test them, especially such extensive changes; I wonder if I removed the imports _after_ starting Gatsby, and it continued using a cached version or something.
=> CACTUS-1008: fix missing import

modules/cactus-web/src/DataGrid/DataGrid.story.tsx, modules/cactus-web/src/helpers/positionPopover.ts
UAT: https://repayonline.atlassian.net/browse/CACTUS-1088
The scroll container changes I made last time broke positioning. I switched from setting top/left OR bottom/right to only ever setting top & left, which gives more consistent behavior.
Also slightly changed the DataGrid story to make it easier to verify that the bug is actually fixed.
=> CACTUS-1088: correct drop-down positioning

modules/cactus-web/src/AccessibleField/AccessibleField.tsx
Ticket: https://repayonline.atlassian.net/browse/CACTUS-1081
I went to change the defaults in the story but thought it was kind of annoying so I left it. Maybe I should add a test or something but other than that not sure what else to change.
=> CACTUS-1081: accessible field autotooltip set to false by default

modules/cactus-web/src/DataGrid/DataGrid.tsx
Ticket: [CACTUS-1099](https://repayonline.atlassian.net/browse/CACTUS-1099)
The issue:
`MenuButton` uses `usePositioning` and passes `positionDropDown` to it which in turn tries to get the scrollParent using a `getScrollParent` function. In the MenuButton, this works as expected, but in DataGrid, it was returning the outermost DataGrid element (StyledDataGrid) because of `overflow-x: auto;`.  Since StyledDataGrid was set to `display: inline;` the clientWidth was 0 (https://www.w3.org/TR/cssom-view/#dom-element-clientwidth). This was causing the min-width to be set to 0.   
```
const visibleWidth = Math.min(scrollParent.clientWidth, view.clientWidth)
const minWidth = Math.min(visibleWidth, button.offsetWidth)
```
I'm a little worried that other things might be set to `display: inline` and …
=> fix(cactus-web): datagrid dropdown issues

modules/cactus-fwk/src/ErrorBoundary.tsx, modules/cactus-i18n/tests/helpers/MockPromise.ts, modules/cactus-web/src/Accordion/Accordion.test.tsx, modules/cactus-web/src/Accordion/Accordion.tsx, modules/cactus-web/src/BrandBar/BrandBar.tsx, modules/cactus-web/src/Calendar/Calendar.tsx, modules/cactus-web/src/Checkable/Group.tsx, modules/cactus-web/src/ColorPicker/ColorPicker.tsx, modules/cactus-web/src/Select/Select.test.tsx, modules/cactus-web/src/Select/Select.tsx, modules/cactus-web/src/helpers/keyCodes.ts, package.json, yarn.lock
https://repayonline.atlassian.net/browse/CACTUS-1091
Upgraded some dependencies to get rid of some security vulnerabilities. I couldn't get rid of all of them; some required a storybook upgrade and after working on that for several hours yesterday, I decided it wasn't worth the time for this ticket since I only had 2 days and those vulnerabilities only affect storybook and gatsby.
Other than that, there are a few other minor refactors in here to address some code smells. `event.keyCode` and `event.which` are both deprecated, so I got rid of the last references to them in this repo.
I'd say the main thing to test would be the keyboard interactions on accordions and the select component. Make sure the arrows, home/end, space/enter keys all work as expected for the accordions and the select …
=> CACTUS-1091 :: Snyk/SonarQube Fixes

.github/workflows/continuous-integration.yml, modules/cactus-web/src/DateInput/DateInput.story.tsx, modules/cactus-web/src/DateInput/DateInput.test.tsx, modules/cactus-web/src/DateInput/DateInput.tsx, modules/cactus-web/src/helpers/dates.ts
Ticket & UAT: https://repayonline.atlassian.net/browse/CACTUS-1113 
This didn't go quite as planned. Basically, to let the user accidentally put in wrong dates I removed all of that weird logic, and have it auto tab if they type '04' instead of '4', I had to keep track of everything as strings (which means the date object now has month and _month). That started a chain reaction of having to update crap everywhere. Like now the string had to be different from the stored value, etc. and I had to switch from the hour dictating the AM/PM value to the AM/PM value dictating the hour value. I also had to update misc stuff here and there.
I'll write more later but in the mean time, there are 2 tests I didn't fix because I'm worried this might be a breaking change after all. If you run `yarn web …
=> cactus-1113-dateinput-auto-tabbing

modules/cactus-form/package.json, yarn.lock
[Ticket](https://repayonline.atlassian.net/browse/CACTUS-1161)
This was a little tricky to figure out. The error message in the action was telling me the problem was that there was no `node_modules` folder in `cactus-form`, so I thought I'd just need to install before running the scan. But even after installing, it was still failing. After going and finding the PR that started the failures, I noticed that it was the one where `final-form` and `react-final-form` were removed from `peerDependencies` and added as `dependencies`. Upon further inspection, I found that those two dependencies were still listed as `devDependencies`, which seems to be what was causing the issue -- even locally, installing wasn't creating a `node_modules` folder. Removing them from `devDependencies` caused them to …
=> CACTUS-1161 :: Fix Snyk Scan

.github/workflows/continuous-integration.yml, .github/workflows/master-workflow.yml
The CI / master pipelines were failing because something updated the node version. Node was reverted to 16 so everything would pass again
Previous failing pipelines: 
1. https://github.com/repaygithub/cactus/actions/runs/4326887317
2. https://github.com/repaygithub/cactus/actions/runs/4326887323
=> revert node version in ci + master pipelines

modules/cactus-web/src/DateInput/DateInput.test.tsx, modules/cactus-web/src/helpers/dates.ts
[Ticket](https://repayonline.atlassian.net/browse/RC-5540)
See ticket details if you want to reproduce the issue in channels. Otherwise, you can reproduce with cactus locally:
- Make sure you're on master branch.
- Start the cactus storybook.
- Update `ControlledWithDate` in `DateInput.story.tsx`:
```sh
export const ControlledWithDate: DateStory = (args) => {
const [value, setValue] = React.useState<Date | string | null>(new Date(2024, 0, 10, 14))
return (
<>
<DateInput
{...args}
name={args.name || args.type}
type="datetime"
value={value}
onChange={args.onChange.wrap(setValue, true)}
/>
<Button mt={4} onClick={() => setValue(null)}>
Clear
</Button>
</>
)
}
```
- Open the DateInput story and note the time portion of the input has "14:00 PM" (it is supposed to be "02:00 PM").
- Update …
=> RC-5540 Fix DateInput time parsing with controlled value
